/*
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Open Digital Public Infrastructure (DPI) Platform
 * Copyright (C) 2025 Open Digital Public Infrastructure (DPI) Platform Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 */
package com.examplatform.questionbank.ai.generation.multiagent;

import com.examplatform.questionbank.ai.generation.QuestionGenerationRequest;
import com.examplatform.questionbank.ai.parser.NormalizedSampleQuestion;
import com.examplatform.questionbank.repository.SimilarityResult;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

import java.util.List;

/**
 * 2. [Question Author Agent]
 * Synthesizes new original items conforming strictly to the blueprint generated by
 * the {@link RequirementAnalystAgent} and guided by few-shot sample demonstrations.
 */
@Slf4j
@Component
@RequiredArgsConstructor
public class QuestionAuthorAgent {

    public String buildPromptWithBlueprint(
            String blueprint,
            QuestionGenerationRequest request,
            List<NormalizedSampleQuestion> sampleQuestions) {
        return buildPromptWithBlueprint(blueprint, request, sampleQuestions, List.of());
    }

    /**
     * Constructs a specialized prompt incorporating blueprint directives, few-shot sample questions,
     * and RAG existing questions to prevent duplicate question generation.
     */
    public String buildPromptWithBlueprint(
            String blueprint,
            QuestionGenerationRequest request,
            List<NormalizedSampleQuestion> sampleQuestions,
            List<SimilarityResult> ragContext) {

        StringBuilder prompt = new StringBuilder();
        prompt.append(blueprint).append("\n\n");
        prompt.append("TASK: Generate ").append(request.getCount())
                .append(" original, high-quality question(s) strictly aligning with the blueprint above.\n");

        if (sampleQuestions != null && !sampleQuestions.isEmpty()) {
            prompt.append("\nFEW-SHOT REFERENCE DEMONSTRATIONS (Study style, depth, and notation; DO NOT duplicate):\n");
            for (int i = 0; i < sampleQuestions.size(); i++) {
                NormalizedSampleQuestion sq = sampleQuestions.get(i);
                prompt.append("--- Demonstration ").append(i + 1).append(" ---\n");
                prompt.append("Stem: ").append(sq.getStem()).append("\n");
                if (sq.getOptions() != null && !sq.getOptions().isEmpty()) {
                    prompt.append("Options:\n");
                    for (var opt : sq.getOptions()) {
                        prompt.append("  ").append(opt.getId()).append(") ").append(opt.getText()).append("\n");
                    }
                }
                if (sq.getAnswerKey() != null) {
                    prompt.append("Answer Key: ").append(sq.getAnswerKey()).append("\n");
                }
            }
        }

        if (ragContext != null && !ragContext.isEmpty()) {
            prompt.append("\nEXISTING QUESTIONS TO AVOID DUPLICATING (Top-N Vector Search Context):\n");
            for (int i = 0; i < ragContext.size(); i++) {
                SimilarityResult ctx = ragContext.get(i);
                prompt.append(i + 1).append(". ").append(ctx.getContent()).append("\n");
            }
        }

        prompt.append("\nOutput ONLY the JSON array of question objects as specified in system instructions.");
        return prompt.toString();
    }
}
