CREATE SCHEMA IF NOT EXISTS delivery_service;

-- ============================================================
-- Table: exam_session
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
CREATE TABLE delivery_service.exam_session (
    id                      UUID PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    session_id              UUID NOT NULL UNIQUE,
    candidate_id            UUID NOT NULL,
    exam_id                 UUID NOT NULL,
    shift_id                UUID NOT NULL,
    paper_id                UUID NOT NULL,
    status                  VARCHAR(20) NOT NULL,
    started_at              TIMESTAMP NOT NULL,
    scheduled_end_at        TIMESTAMP NOT NULL,
    current_question_index  INTEGER NOT NULL,
    language_code           VARCHAR(10) NOT NULL,
    full_screen_exit_count  INTEGER NOT NULL,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    version                 BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_exam_session_tenant_id ON delivery_service.exam_session(tenant_id);
CREATE INDEX idx_exam_session_candidate_id ON delivery_service.exam_session(candidate_id);
CREATE INDEX idx_exam_session_exam_id ON delivery_service.exam_session(exam_id);
CREATE INDEX idx_exam_session_status ON delivery_service.exam_session(status);
