CREATE SCHEMA IF NOT EXISTS asset_service;

-- ============================================================
-- Table: media_asset
-- ============================================================
-- Stores metadata for all multimedia assets. Binary content is
-- stored externally via a pluggable storage provider.
-- IDs are UUID v7, generated by the application before insert.
CREATE TABLE asset_service.media_asset (
    id                  UUID PRIMARY KEY,
    tenant_id           VARCHAR(255) NOT NULL,

    -- File identity
    original_filename   VARCHAR(500) NOT NULL,
    content_type        VARCHAR(100) NOT NULL,
    extension           VARCHAR(20),
    file_size           BIGINT NOT NULL,
    sha256_hash         VARCHAR(64) NOT NULL,

    -- Classification
    asset_type          VARCHAR(20) NOT NULL,
    status              VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',

    -- Image metadata
    width               INTEGER,
    height              INTEGER,
    dpi                 INTEGER,
    orientation         VARCHAR(20),

    -- Audio/Video metadata
    duration_seconds    DOUBLE PRECISION,
    codec               VARCHAR(50),
    bitrate             INTEGER,
    sample_rate         INTEGER,
    channels            INTEGER,
    frame_rate          DOUBLE PRECISION,

    -- User-supplied metadata
    title               VARCHAR(500),
    description         TEXT,
    alt_text            VARCHAR(1000),
    tags                VARCHAR(2000),
    language            VARCHAR(10),

    -- Storage reference
    storage_provider    VARCHAR(50) NOT NULL,
    storage_location    VARCHAR(2000) NOT NULL,

    -- Authoring
    created_by          UUID NOT NULL,

    -- BaseEntity fields
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    version             BIGINT NOT NULL DEFAULT 0
);

-- Indexes for common query patterns
CREATE INDEX idx_media_asset_tenant_id ON asset_service.media_asset(tenant_id);
CREATE INDEX idx_media_asset_sha256_hash ON asset_service.media_asset(sha256_hash);
CREATE INDEX idx_media_asset_asset_type ON asset_service.media_asset(asset_type);
CREATE INDEX idx_media_asset_status ON asset_service.media_asset(status);
CREATE INDEX idx_media_asset_created_by ON asset_service.media_asset(created_by);
CREATE INDEX idx_media_asset_content_type ON asset_service.media_asset(content_type);
CREATE INDEX idx_media_asset_created_at ON asset_service.media_asset(created_at);

-- Unique constraint: same file (by hash) within a tenant
CREATE UNIQUE INDEX idx_media_asset_hash_tenant ON asset_service.media_asset(sha256_hash, tenant_id)
    WHERE status <> 'DELETED';

-- ============================================================
-- Table: asset_reference
-- ============================================================
-- Tracks where assets are used across the platform.
-- Prevents deletion of referenced assets.
CREATE TABLE asset_service.asset_reference (
    id                  UUID PRIMARY KEY,
    tenant_id           VARCHAR(255) NOT NULL,
    asset_id            UUID NOT NULL,
    reference_type      VARCHAR(30) NOT NULL,
    reference_id        UUID NOT NULL,
    created_by          UUID NOT NULL,

    -- BaseEntity fields
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    version             BIGINT NOT NULL DEFAULT 0,

    -- Foreign key to media_asset
    CONSTRAINT fk_asset_reference_asset FOREIGN KEY (asset_id)
        REFERENCES asset_service.media_asset(id) ON DELETE RESTRICT
);

CREATE INDEX idx_asset_reference_tenant_id ON asset_service.asset_reference(tenant_id);
CREATE INDEX idx_asset_reference_asset_id ON asset_service.asset_reference(asset_id);
CREATE INDEX idx_asset_reference_ref ON asset_service.asset_reference(reference_type, reference_id);

-- Unique constraint: one reference per (asset, type, entity)
CREATE UNIQUE INDEX idx_asset_reference_unique ON asset_service.asset_reference(asset_id, reference_type, reference_id);
