-- SPDX-License-Identifier: AGPL-3.0-only
--
-- National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
-- Copyright (C) 2025 NAG Contributors

CREATE SCHEMA IF NOT EXISTS identity_service;

-- ============================================================
-- Table: user_account
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
CREATE TABLE identity_service.user_account (
    id                  UUID PRIMARY KEY,
    tenant_id           VARCHAR(255) NOT NULL,
    username            VARCHAR(255) NOT NULL,
    email_hash          VARCHAR(255) NOT NULL,
    mobile_hash         VARCHAR(255) NOT NULL,
    identity_doc_type   VARCHAR(50),
    identity_doc_hash   VARCHAR(255),
    identity_doc_hmac   VARCHAR(255),
    account_status      VARCHAR(50),
    mfa_enabled         BOOLEAN NOT NULL DEFAULT FALSE,
    mfa_secret_ref      VARCHAR(255),
    device_fingerprint  VARCHAR(255),
    failed_attempt_count INTEGER NOT NULL DEFAULT 0,
    last_failed_at      TIMESTAMP,
    locked_at           TIMESTAMP,
    keycloak_user_id    VARCHAR(255),
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    version             BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_user_account_tenant_id ON identity_service.user_account(tenant_id);
CREATE INDEX idx_user_account_email_hash ON identity_service.user_account(email_hash);
CREATE INDEX idx_user_account_mobile_hash ON identity_service.user_account(mobile_hash);
CREATE INDEX idx_user_account_keycloak_user_id ON identity_service.user_account(keycloak_user_id);

-- ============================================================
-- Table: otp_verification
-- ============================================================
CREATE TABLE identity_service.otp_verification (
    id          UUID PRIMARY KEY,
    tenant_id   VARCHAR(255) NOT NULL,
    user_id     UUID,
    mobile_hash VARCHAR(255) NOT NULL,
    otp_hash    VARCHAR(255) NOT NULL,
    expires_at  TIMESTAMP NOT NULL,
    verified    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    version     BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_otp_verification_tenant_id ON identity_service.otp_verification(tenant_id);
CREATE INDEX idx_otp_verification_mobile_hash ON identity_service.otp_verification(mobile_hash);
CREATE INDEX idx_otp_verification_user_id ON identity_service.otp_verification(user_id);

-- ============================================================
-- Table: user_role_assignment
-- ============================================================
CREATE TABLE identity_service.user_role_assignment (
    id          UUID PRIMARY KEY,
    tenant_id   VARCHAR(255) NOT NULL,
    user_id     UUID NOT NULL,
    role        VARCHAR(50) NOT NULL,
    assigned_by UUID,
    assigned_at TIMESTAMP,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    version     BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_user_role_assignment_tenant_id ON identity_service.user_role_assignment(tenant_id);
CREATE INDEX idx_user_role_assignment_user_id ON identity_service.user_role_assignment(user_id);

-- ============================================================
-- Table: webauthn_credential
-- ============================================================
CREATE TABLE identity_service.webauthn_credential (
    id              UUID PRIMARY KEY,
    tenant_id       VARCHAR(255) NOT NULL,
    user_id         UUID NOT NULL,
    credential_id   VARCHAR(255) NOT NULL UNIQUE,
    public_key_cose BYTEA,
    sign_count      BIGINT NOT NULL DEFAULT 0,
    aaguid          VARCHAR(255),
    created_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMP NOT NULL DEFAULT NOW(),
    version         BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_webauthn_credential_tenant_id ON identity_service.webauthn_credential(tenant_id);
CREATE INDEX idx_webauthn_credential_user_id ON identity_service.webauthn_credential(user_id);

-- ============================================================
-- Table: active_session
-- ============================================================
CREATE TABLE identity_service.active_session (
    id            UUID PRIMARY KEY,
    tenant_id     VARCHAR(255) NOT NULL,
    user_id       UUID NOT NULL,
    session_token VARCHAR(512) NOT NULL,
    device_fp     VARCHAR(512),
    ip_address    VARCHAR(255),
    expires_at    TIMESTAMP NOT NULL,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    version       BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_active_session_tenant_id ON identity_service.active_session(tenant_id);
CREATE INDEX idx_active_session_user_id ON identity_service.active_session(user_id);
CREATE INDEX idx_active_session_expires_at ON identity_service.active_session(expires_at);

-- ============================================================
-- Table: role_definition
-- Stores configurable role definitions (beyond the fixed enum).
-- ============================================================
CREATE TABLE identity_service.role_definition (
    id          UUID PRIMARY KEY,
    tenant_id   VARCHAR(255) NOT NULL,
    name        VARCHAR(100) NOT NULL,
    code        VARCHAR(50)  NOT NULL,
    description VARCHAR(500),
    active      BOOLEAN NOT NULL DEFAULT TRUE,
    system_role BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    version     BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_role_definition_code_tenant
    ON identity_service.role_definition(code, tenant_id);
CREATE INDEX idx_role_definition_tenant_id
    ON identity_service.role_definition(tenant_id);
CREATE INDEX idx_role_definition_active
    ON identity_service.role_definition(active);

-- ============================================================
-- Table: permission
-- Stores granular permission definitions.
-- ============================================================
CREATE TABLE identity_service.permission (
    id          UUID PRIMARY KEY,
    tenant_id   VARCHAR(255) NOT NULL,
    code        VARCHAR(100) NOT NULL,
    name        VARCHAR(200) NOT NULL,
    description VARCHAR(500),
    module      VARCHAR(100) NOT NULL,
    created_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMP NOT NULL DEFAULT NOW(),
    version     BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_permission_code_tenant
    ON identity_service.permission(code, tenant_id);
CREATE INDEX idx_permission_tenant_id
    ON identity_service.permission(tenant_id);
CREATE INDEX idx_permission_module
    ON identity_service.permission(module);

-- ============================================================
-- Table: role_permission (join table)
-- Maps roles to their permissions.
-- ============================================================
CREATE TABLE identity_service.role_permission (
    id            UUID PRIMARY KEY,
    tenant_id     VARCHAR(255) NOT NULL,
    role_id       UUID NOT NULL REFERENCES identity_service.role_definition(id) ON DELETE CASCADE,
    permission_id UUID NOT NULL REFERENCES identity_service.permission(id) ON DELETE CASCADE,
    created_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at    TIMESTAMP NOT NULL DEFAULT NOW(),
    version       BIGINT NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_role_permission_unique
    ON identity_service.role_permission(role_id, permission_id, tenant_id);
CREATE INDEX idx_role_permission_role_id
    ON identity_service.role_permission(role_id);
CREATE INDEX idx_role_permission_permission_id
    ON identity_service.role_permission(permission_id);

-- ============================================================
-- Seed system roles (matching existing UserRole enum values)
-- ============================================================
INSERT INTO identity_service.role_definition (id, tenant_id, name, code, description, active, system_role)
VALUES
    (gen_random_uuid(), 'default', 'Super Admin', 'SUPER_ADMIN', 'Full system access with all permissions', TRUE, TRUE),
    (gen_random_uuid(), 'default', 'Security Admin', 'SECURITY_ADMIN', 'Manages security policies and user access', TRUE, TRUE),
    (gen_random_uuid(), 'default', 'Question Author', 'QUESTION_AUTHOR', 'Creates and edits examination questions', TRUE, TRUE),
    (gen_random_uuid(), 'default', 'Reviewer', 'REVIEWER', 'Reviews and validates questions', TRUE, TRUE),
    (gen_random_uuid(), 'default', 'Approver', 'APPROVER', 'Approves questions and papers for publication', TRUE, TRUE),
    (gen_random_uuid(), 'default', 'Exam Controller', 'EXAM_CONTROLLER', 'Manages examination scheduling and delivery', TRUE, TRUE),
    (gen_random_uuid(), 'default', 'Translator', 'TRANSLATOR', 'Translates questions to regional languages', TRUE, TRUE),
    (gen_random_uuid(), 'default', 'Evaluator', 'EVALUATOR', 'Evaluates subjective responses', TRUE, TRUE),
    (gen_random_uuid(), 'default', 'Auditor', 'AUDITOR', 'Views audit trails and compliance reports', TRUE, TRUE),
    (gen_random_uuid(), 'default', 'Candidate', 'CANDIDATE', 'Takes examinations and views results', TRUE, TRUE);

-- =============================================================================
-- Seed Platform Permissions
-- =============================================================================
INSERT INTO identity_service.permission (id, tenant_id, code, name, description, module)
VALUES
    -- IDENTITY Module
    ('018f4e2b-0001-7000-8000-000000000001', 'default', 'IDENTITY:USER_READ', 'View Users', 'View user accounts, statuses, and profiles', 'IDENTITY'),
    ('018f4e2b-0001-7000-8000-000000000002', 'default', 'IDENTITY:USER_WRITE', 'Manage Users', 'Create, update, and deactivate user accounts', 'IDENTITY'),
    ('018f4e2b-0001-7000-8000-000000000003', 'default', 'IDENTITY:ROLE_READ', 'View Roles', 'View role definitions, details, and permission mappings', 'IDENTITY'),
    ('018f4e2b-0001-7000-8000-000000000004', 'default', 'IDENTITY:ROLE_MANAGE', 'Manage Roles', 'Create, update, and delete custom roles and assign permissions', 'IDENTITY'),
    ('018f4e2b-0001-7000-8000-000000000005', 'default', 'IDENTITY:USER_ROLE_ASSIGN', 'Assign Roles', 'Assign and revoke roles for platform users', 'IDENTITY'),
    ('018f4e2b-0001-7000-8000-000000000006', 'default', 'IDENTITY:MFA_MANAGE', 'Manage MFA', 'Configure and reset Multi-Factor Authentication for users', 'IDENTITY'),

    -- QUESTION_BANK Module
    ('018f4e2b-0002-7000-8000-000000000001', 'default', 'QUESTION:READ', 'View Questions', 'Browse, search, and inspect question items', 'QUESTION_BANK'),
    ('018f4e2b-0002-7000-8000-000000000002', 'default', 'QUESTION:CREATE', 'Create Questions', 'Author and draft new questions in question bank', 'QUESTION_BANK'),
    ('018f4e2b-0002-7000-8000-000000000003', 'default', 'QUESTION:EDIT', 'Edit Questions', 'Modify drafted questions, choices, and metadata', 'QUESTION_BANK'),
    ('018f4e2b-0002-7000-8000-000000000004', 'default', 'QUESTION:DELETE', 'Delete Questions', 'Remove questions from the question bank', 'QUESTION_BANK'),
    ('018f4e2b-0002-7000-8000-000000000005', 'default', 'QUESTION:REVIEW', 'Review Questions', 'Perform peer review, rubric check, and question validation', 'QUESTION_BANK'),
    ('018f4e2b-0002-7000-8000-000000000006', 'default', 'QUESTION:APPROVE', 'Approve Questions', 'Approve reviewed questions for publication in blueprints', 'QUESTION_BANK'),
    ('018f4e2b-0002-7000-8000-000000000007', 'default', 'QUESTION:TRANSLATE', 'Translate Questions', 'Translate questions and options into regional languages', 'QUESTION_BANK'),
    ('018f4e2b-0002-7000-8000-000000000008', 'default', 'QUESTION:IMPORT_EXPORT', 'Import/Export Questions', 'Bulk import and export question banks (CSV, JSON, QTI)', 'QUESTION_BANK'),

    -- EXAM_MANAGEMENT Module
    ('018f4e2b-0003-7000-8000-000000000001', 'default', 'EXAM:READ', 'View Examinations', 'Browse and view exam blueprints and schedules', 'EXAM_MANAGEMENT'),
    ('018f4e2b-0003-7000-8000-000000000002', 'default', 'EXAM:CREATE', 'Create Examinations', 'Define new examination blueprints and paper templates', 'EXAM_MANAGEMENT'),
    ('018f4e2b-0003-7000-8000-000000000003', 'default', 'EXAM:SCHEDULE', 'Schedule Examinations', 'Configure time slots, test centers, and candidate allocations', 'EXAM_MANAGEMENT'),
    ('018f4e2b-0003-7000-8000-000000000004', 'default', 'EXAM:PUBLISH', 'Publish Examinations', 'Publish exam schedules for candidate registration', 'EXAM_MANAGEMENT'),
    ('018f4e2b-0003-7000-8000-000000000005', 'default', 'EXAM:CANCEL', 'Cancel Examinations', 'Cancel scheduled examination sessions and notify candidates', 'EXAM_MANAGEMENT'),

    -- EXAM_DELIVERY Module
    ('018f4e2b-0004-7000-8000-000000000001', 'default', 'DELIVERY:MONITOR', 'Live Monitoring', 'Monitor live exam sessions, heartbeats, and delivery status', 'EXAM_DELIVERY'),
    ('018f4e2b-0004-7000-8000-000000000002', 'default', 'DELIVERY:ATTEND', 'Attend Exam', 'Launch candidate exam interface and submit responses', 'EXAM_DELIVERY'),
    ('018f4e2b-0004-7000-8000-000000000003', 'default', 'DELIVERY:PROCTOR', 'Proctor Exam', 'Live proctoring oversight, anomaly flagging, and session controls', 'EXAM_DELIVERY'),
    ('018f4e2b-0004-7000-8000-000000000004', 'default', 'DELIVERY:RETEST', 'Authorize Retest', 'Issue retest authorization for affected candidates', 'EXAM_DELIVERY'),

    -- ASSESSMENT_EVALUATION Module
    ('018f4e2b-0005-7000-8000-000000000001', 'default', 'EVALUATION:READ', 'View Evaluation', 'Access candidate response sheets and answer keys', 'ASSESSMENT_EVALUATION'),
    ('018f4e2b-0005-7000-8000-000000000002', 'default', 'EVALUATION:SCORE_AUTO', 'Execute Auto-Grading', 'Run automated grading pipeline on objective responses', 'ASSESSMENT_EVALUATION'),
    ('018f4e2b-0005-7000-8000-000000000003', 'default', 'EVALUATION:SCORE_MANUAL', 'Manual Scoring', 'Evaluate subjective and descriptive candidate responses', 'ASSESSMENT_EVALUATION'),
    ('018f4e2b-0005-7000-8000-000000000004', 'default', 'EVALUATION:RESULT_PUBLISH', 'Publish Results', 'Approve final scorecards and publish merit lists', 'ASSESSMENT_EVALUATION'),

    -- AUDIT_SECURITY Module
    ('018f4e2b-0006-7000-8000-000000000001', 'default', 'AUDIT:READ', 'View Audit Logs', 'Inspect immutable audit trails and system event logs', 'AUDIT_SECURITY'),
    ('018f4e2b-0006-7000-8000-000000000002', 'default', 'AUDIT:EXPORT', 'Export Audit Logs', 'Export compliance and security audit logs', 'AUDIT_SECURITY'),
    ('018f4e2b-0006-7000-8000-000000000003', 'default', 'SECURITY:POLICY_MANAGE', 'Manage Security Policies', 'Configure password rules, IP restrictions, and session parameters', 'AUDIT_SECURITY'),

    -- ANALYTICS_REPORTS Module
    ('018f4e2b-0007-7000-8000-000000000001', 'default', 'ANALYTICS:VIEW', 'View Analytics', 'Access platform metrics, exam statistics, and item analysis', 'ANALYTICS_REPORTS'),
    ('018f4e2b-0007-7000-8000-000000000002', 'default', 'REPORTS:EXPORT', 'Export Reports', 'Generate and download administrative reports and insights', 'ANALYTICS_REPORTS')
ON CONFLICT (id) DO NOTHING;

-- =============================================================================
-- Map Permissions to Default System Roles
-- =============================================================================

-- SUPER_ADMIN: Receives ALL permissions
INSERT INTO identity_service.role_permission (id, tenant_id, role_id, permission_id)
SELECT
    gen_random_uuid(),
    'default',
    r.id,
    p.id
FROM identity_service.role_definition r
CROSS JOIN identity_service.permission p
WHERE r.code = 'SUPER_ADMIN'
ON CONFLICT (role_id, permission_id, tenant_id) DO NOTHING;

-- SECURITY_ADMIN: Identity, Audit, Security, Analytics
INSERT INTO identity_service.role_permission (id, tenant_id, role_id, permission_id)
SELECT
    gen_random_uuid(),
    'default',
    r.id,
    p.id
FROM identity_service.role_definition r
JOIN identity_service.permission p ON p.module IN ('IDENTITY', 'AUDIT_SECURITY', 'ANALYTICS_REPORTS')
WHERE r.code = 'SECURITY_ADMIN'
ON CONFLICT (role_id, permission_id, tenant_id) DO NOTHING;

-- QUESTION_AUTHOR: Question read, create, edit, import/export
INSERT INTO identity_service.role_permission (id, tenant_id, role_id, permission_id)
SELECT
    gen_random_uuid(),
    'default',
    r.id,
    p.id
FROM identity_service.role_definition r
JOIN identity_service.permission p ON p.code IN ('QUESTION:READ', 'QUESTION:CREATE', 'QUESTION:EDIT', 'QUESTION:IMPORT_EXPORT')
WHERE r.code = 'QUESTION_AUTHOR'
ON CONFLICT (role_id, permission_id, tenant_id) DO NOTHING;

-- REVIEWER: Question read, review
INSERT INTO identity_service.role_permission (id, tenant_id, role_id, permission_id)
SELECT
    gen_random_uuid(),
    'default',
    r.id,
    p.id
FROM identity_service.role_definition r
JOIN identity_service.permission p ON p.code IN ('QUESTION:READ', 'QUESTION:REVIEW')
WHERE r.code = 'REVIEWER'
ON CONFLICT (role_id, permission_id, tenant_id) DO NOTHING;

-- APPROVER: Question read, approve, Exam read
INSERT INTO identity_service.role_permission (id, tenant_id, role_id, permission_id)
SELECT
    gen_random_uuid(),
    'default',
    r.id,
    p.id
FROM identity_service.role_definition r
JOIN identity_service.permission p ON p.code IN ('QUESTION:READ', 'QUESTION:APPROVE', 'EXAM:READ')
WHERE r.code = 'APPROVER'
ON CONFLICT (role_id, permission_id, tenant_id) DO NOTHING;

-- EXAM_CONTROLLER: Exams, Delivery monitoring, proctoring, retest, result publish, analytics, reports
INSERT INTO identity_service.role_permission (id, tenant_id, role_id, permission_id)
SELECT
    gen_random_uuid(),
    'default',
    r.id,
    p.id
FROM identity_service.role_definition r
JOIN identity_service.permission p ON p.module IN ('EXAM_MANAGEMENT', 'EXAM_DELIVERY', 'ANALYTICS_REPORTS')
    OR p.code = 'EVALUATION:RESULT_PUBLISH'
WHERE r.code = 'EXAM_CONTROLLER'
ON CONFLICT (role_id, permission_id, tenant_id) DO NOTHING;

-- TRANSLATOR: Question read, translate
INSERT INTO identity_service.role_permission (id, tenant_id, role_id, permission_id)
SELECT
    gen_random_uuid(),
    'default',
    r.id,
    p.id
FROM identity_service.role_definition r
JOIN identity_service.permission p ON p.code IN ('QUESTION:READ', 'QUESTION:TRANSLATE')
WHERE r.code = 'TRANSLATOR'
ON CONFLICT (role_id, permission_id, tenant_id) DO NOTHING;

-- EVALUATOR: Evaluation read, manual scoring
INSERT INTO identity_service.role_permission (id, tenant_id, role_id, permission_id)
SELECT
    gen_random_uuid(),
    'default',
    r.id,
    p.id
FROM identity_service.role_definition r
JOIN identity_service.permission p ON p.code IN ('EVALUATION:READ', 'EVALUATION:SCORE_MANUAL')
WHERE r.code = 'EVALUATOR'
ON CONFLICT (role_id, permission_id, tenant_id) DO NOTHING;

-- AUDITOR: Audit read, export, analytics, reports
INSERT INTO identity_service.role_permission (id, tenant_id, role_id, permission_id)
SELECT
    gen_random_uuid(),
    'default',
    r.id,
    p.id
FROM identity_service.role_definition r
JOIN identity_service.permission p ON p.module IN ('AUDIT_SECURITY', 'ANALYTICS_REPORTS')
WHERE r.code = 'AUDITOR'
ON CONFLICT (role_id, permission_id, tenant_id) DO NOTHING;

-- CANDIDATE: Attend exam, read results
INSERT INTO identity_service.role_permission (id, tenant_id, role_id, permission_id)
SELECT
    gen_random_uuid(),
    'default',
    r.id,
    p.id
FROM identity_service.role_definition r
JOIN identity_service.permission p ON p.code IN ('DELIVERY:ATTEND', 'EVALUATION:READ')
WHERE r.code = 'CANDIDATE'
ON CONFLICT (role_id, permission_id, tenant_id) DO NOTHING;

-- =============================================================================
-- Seed Data — Test users and roles for development
-- =============================================================================
INSERT INTO identity_service.user_account (
    id, tenant_id, username, email_hash, mobile_hash,
    account_status, mfa_enabled, failed_attempt_count,
    created_at, updated_at, version
) VALUES
('018f4e2a-0000-7000-8000-000000000001', 'default', 'superadmin',
 '186cf774c97b60a1c106ef718d10970a6a06e06bef89553d9ae65d938a886eae',
 'a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2c3d4e5f6a1b2',
 'ACTIVE', false, 0, NOW(), NOW(), 0),
('018f4e2a-0000-7000-8000-000000000002', 'default', 'secadmin',
 '429143a61064c974ed58080b7d7ea39cf806571abf7ec5f9f79f0faba5f1ec0b',
 'b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2',
 'ACTIVE', false, 0, NOW(), NOW(), 0),
('018f4e2a-0000-7000-8000-000000000003', 'default', 'author1',
 '1d0e1b1bd678143a050f6cb90e6ebdfd2927c81b1321e1fc01f2e2490f1459c7',
 'c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3',
 'ACTIVE', false, 0, NOW(), NOW(), 0),
('018f4e2a-0000-7000-8000-000000000004', 'default', 'reviewer1',
 '674ea6de0c758c87a3a9156288164e9781ae2d5cf765824c4e2ee7ed0756b73a',
 'd3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4',
 'ACTIVE', false, 0, NOW(), NOW(), 0),
('018f4e2a-0000-7000-8000-000000000005', 'default', 'controller1',
 '3bf7bd3a4c57518cb4d1622284d6b4b6769b6a1c3b5973ae770226f7b5ba839b',
 'e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5',
 'ACTIVE', false, 0, NOW(), NOW(), 0),
('018f4e2a-0000-7000-8000-000000000006', 'default', 'candidate1',
 'e75c44736ae122cf1ec886b703515008e1be7dd934cdf94239d7edb202eb52df',
 'f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6',
 'ACTIVE', false, 0, NOW(), NOW(), 0),
('018f4e2a-0000-7000-8000-000000000007', 'default', 'translator1',
 '24d1de25d350ae44f9ac21ca873d279f37b05c5cb59b8e71b6c136f8d1ff7df6',
 'a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1',
 'ACTIVE', false, 0, NOW(), NOW(), 0),
('018f4e2a-0000-7000-8000-000000000008', 'default', 'evaluator1',
 'baec845d9fd8d0728a11a32c237f79edec6bc30d416b01f97ba255998746ab79',
 'b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b100',
 'ACTIVE', false, 0, NOW(), NOW(), 0),
('018f4e2a-0000-7000-8000-000000000009', 'default', 'auditor1',
 'a8e7654aed6072f7d449a51607c5164bfdc3bb0f96b2d83f978f526ce9d2b576',
 'c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c200',
 'ACTIVE', false, 0, NOW(), NOW(), 0),
('018f4e2a-0000-7000-8000-00000000000a', 'default', 'approver1',
 'e973de4808e055b3238a774fbfba4bea8f563b24ff0d60fdb84023588251786f',
 'd3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d3e4f5a6b1c2d300',
 'ACTIVE', false, 0, NOW(), NOW(), 0)
ON CONFLICT (id) DO NOTHING;

INSERT INTO identity_service.user_role_assignment (
    id, tenant_id, user_id, role, assigned_by, assigned_at,
    created_at, updated_at, version
) VALUES
('018f4e2a-0000-7001-8000-000000000001', 'default',
 '018f4e2a-0000-7000-8000-000000000001', 'SUPER_ADMIN', NULL, NOW(), NOW(), NOW(), 0),
('018f4e2a-0000-7001-8000-000000000002', 'default',
 '018f4e2a-0000-7000-8000-000000000002', 'SECURITY_ADMIN',
 '018f4e2a-0000-7000-8000-000000000001', NOW(), NOW(), NOW(), 0),
('018f4e2a-0000-7001-8000-000000000003', 'default',
 '018f4e2a-0000-7000-8000-000000000003', 'QUESTION_AUTHOR',
 '018f4e2a-0000-7000-8000-000000000001', NOW(), NOW(), NOW(), 0),
('018f4e2a-0000-7001-8000-000000000004', 'default',
 '018f4e2a-0000-7000-8000-000000000004', 'REVIEWER',
 '018f4e2a-0000-7000-8000-000000000001', NOW(), NOW(), NOW(), 0),
('018f4e2a-0000-7001-8000-000000000005', 'default',
 '018f4e2a-0000-7000-8000-000000000005', 'EXAM_CONTROLLER',
 '018f4e2a-0000-7000-8000-000000000001', NOW(), NOW(), NOW(), 0),
('018f4e2a-0000-7001-8000-000000000006', 'default',
 '018f4e2a-0000-7000-8000-000000000006', 'CANDIDATE',
 '018f4e2a-0000-7000-8000-000000000001', NOW(), NOW(), NOW(), 0),
('018f4e2a-0000-7001-8000-000000000007', 'default',
 '018f4e2a-0000-7000-8000-000000000007', 'TRANSLATOR',
 '018f4e2a-0000-7000-8000-000000000001', NOW(), NOW(), NOW(), 0),
('018f4e2a-0000-7001-8000-000000000008', 'default',
 '018f4e2a-0000-7000-8000-000000000008', 'EVALUATOR',
 '018f4e2a-0000-7000-8000-000000000001', NOW(), NOW(), NOW(), 0),
('018f4e2a-0000-7001-8000-000000000009', 'default',
 '018f4e2a-0000-7000-8000-000000000009', 'AUDITOR',
 '018f4e2a-0000-7000-8000-000000000001', NOW(), NOW(), NOW(), 0),
('018f4e2a-0000-7001-8000-00000000000a', 'default',
 '018f4e2a-0000-7000-8000-00000000000a', 'APPROVER',
 '018f4e2a-0000-7000-8000-000000000001', NOW(), NOW(), NOW(), 0)
ON CONFLICT (id) DO NOTHING;
