# SPDX-License-Identifier: AGPL-3.0-only
#
# National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
# Copyright (C) 2025 NAG Contributors

{{- if .Values.frontend.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "examination-platform.fullname" . }}-frontend
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: exam-platform
    app.kubernetes.io/component: frontend
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60"
spec:
  ingressClassName: nginx
  rules:
    - host: "admin.{{ .Values.global.environment }}.exam-platform.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "examination-platform.fullname" . }}-frontend
                port:
                  name: http
{{- end }}
