export * from './profile-overview-card/profile-overview-card.component';
export * from './profile-tab-nav/profile-tab-nav.component';
export * from './personal-details-panel/personal-details-panel.component';
export * from './contact-details-panel/contact-details-panel.component';
export * from './education-details-panel/education-details-panel.component';
export * from './kyc-documents-panel/kyc-documents-panel.component';
export * from './webcam-capture-modal/webcam-capture-modal.component';
export * from './image-cropper-modal/image-cropper-modal.component';
export * from './digilocker-panel/digilocker-panel.component';
