/*
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
 * Copyright (C) 2025 NAG Contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published
 * by the Free Software Foundation, version 3 of the License.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package com.examplatform.analytics.service;

import com.examplatform.analytics.domain.ExamAnalytics;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.apache.pdfbox.Loader;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.text.PDFTextStripper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;

@DisplayName("AnalyticsPdfService Unit Tests")
class AnalyticsPdfServiceTest {

    private AnalyticsPdfService analyticsPdfService;

    @BeforeEach
    void setUp() {
        ObjectMapper objectMapper = new ObjectMapper();
        analyticsPdfService = new AnalyticsPdfService(objectMapper);
    }

    @Test
    @DisplayName("Generates valid structured PDF with all required sections")
    void generatePdfReport_producesValidPdfWithStructuredSections() throws IOException {
        UUID examId = UUID.randomUUID();
        ExamAnalytics analytics = ExamAnalytics.builder()
                .id(UUID.randomUUID())
                .examId(examId)
                .totalRegistered(1000L)
                .totalAppeared(950L)
                .top10PercentileThreshold(BigDecimal.valueOf(88.50))
                .bottom10PercentileThreshold(BigDecimal.valueOf(25.00))
                .scoreDistributionJson("{\"0-10\":10,\"10-20\":40,\"20-30\":100,\"30-40\":200,\"40-50\":300,\"50-60\":150,\"60-70\":80,\"70-80\":45,\"80-90\":20,\"90-100\":5}")
                .sectionAveragesJson("{\"Physics\": 42.50, \"Chemistry\": 38.75, \"Mathematics\": 35.20}")
                .computedAt(Instant.now())
                .build();

        byte[] pdfBytes = analyticsPdfService.generatePdfReport(analytics);

        assertThat(pdfBytes).isNotNull();
        assertThat(pdfBytes.length).isGreaterThan(0);

        try (PDDocument doc = Loader.loadPDF(pdfBytes)) {
            assertThat(doc.getNumberOfPages()).isGreaterThan(0);

            PDFTextStripper stripper = new PDFTextStripper();
            String text = stripper.getText(doc);

            // Verify Header Branding
            assertThat(text).contains("NATIONAL ASSESSMENT GRID (NAG)");
            assertThat(text).contains("Official Post-Exam Performance & Analytics Report");
            assertThat(text).contains(examId.toString());

            // Verify Executive Summary & Key Percentiles
            assertThat(text).contains("1. Executive Summary & Key Percentiles");
            assertThat(text).contains("Total Registered");
            assertThat(text).contains("Total Appeared");
            assertThat(text).contains("Top 10% (P90) Score");
            assertThat(text).contains("Bottom 10% (P10) Score");
            assertThat(text).contains("88.50");
            assertThat(text).contains("25.00");

            // Verify Histogram and intervals
            assertThat(text).contains("2. Score Distribution Histogram");
            assertThat(text).contains("Score Interval");
            assertThat(text).contains("0-10");
            assertThat(text).contains("90-100");

            // Verify Section Table
            assertThat(text).contains("3. Section & Subject Performance Breakdown");
            assertThat(text).contains("Section / Subject Name");
            assertThat(text).contains("Average Score");
            assertThat(text).contains("Physics");
            assertThat(text).contains("42.50");
            assertThat(text).contains("Chemistry");
            assertThat(text).contains("38.75");
            assertThat(text).contains("Mathematics");
            assertThat(text).contains("35.20");

            // Verify Footer
            assertThat(text).contains("Generated by National Assessment Grid (NAG) Analytics Platform");
        }
    }

    @Test
    @DisplayName("Generates valid PDF when section breakdown is empty")
    void generatePdfReport_handlesEmptySections() throws IOException {
        ExamAnalytics analytics = ExamAnalytics.builder()
                .id(UUID.randomUUID())
                .examId(UUID.randomUUID())
                .totalRegistered(10L)
                .totalAppeared(10L)
                .scoreDistributionJson("{}")
                .sectionAveragesJson("{}")
                .computedAt(Instant.now())
                .build();

        byte[] pdfBytes = analyticsPdfService.generatePdfReport(analytics);

        try (PDDocument doc = Loader.loadPDF(pdfBytes)) {
            PDFTextStripper stripper = new PDFTextStripper();
            String text = stripper.getText(doc);
            assertThat(text).contains("No section breakdown data available.");
        }
    }
}
