-- SPDX-License-Identifier: AGPL-3.0-only
--
-- National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
-- Copyright (C) 2025 NAG Contributors

CREATE SCHEMA IF NOT EXISTS response_service;

-- ============================================================
-- Table: response
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
CREATE TABLE response_service.response (
    id                      UUID PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    session_id              UUID NOT NULL,
    question_id             UUID NOT NULL,
    candidate_id            UUID NOT NULL,
    selected_option_ids     JSONB,
    entered_value           TEXT,
    timestamp               TIMESTAMP NOT NULL,
    cumulative_time_spent_ms BIGINT NOT NULL,
    revision_sequence       INTEGER NOT NULL,
    save_source             VARCHAR(20) NOT NULL,
    is_final                BOOLEAN NOT NULL DEFAULT FALSE,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    version                 BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_response_tenant_id ON response_service.response(tenant_id);
CREATE INDEX idx_response_session_id ON response_service.response(session_id);
CREATE INDEX idx_response_candidate_id ON response_service.response(candidate_id);
CREATE INDEX idx_response_session_question ON response_service.response(session_id, question_id, revision_sequence DESC);
CREATE INDEX idx_response_candidate_final ON response_service.response(candidate_id) WHERE is_final = TRUE;
