-- SPDX-License-Identifier: AGPL-3.0-only
--
-- National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
-- Copyright (C) 2025 NAG Contributors

CREATE SCHEMA IF NOT EXISTS paper_generator;

-- ============================================================
-- Table: paper
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
-- created_at / updated_at are set by BaseEntity @PrePersist / @PreUpdate;
-- no DEFAULT NOW() so the DB never silently overrides application values.
CREATE TABLE paper_generator.paper (
    id                      UUID         PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    exam_id                 UUID         NOT NULL,
    shift_id                VARCHAR(255) NOT NULL,
    status                  VARCHAR(20)  NOT NULL,
    paper_definition_json   JSONB,
    difficulty_score        DOUBLE PRECISION,
    topic_distribution_json JSONB,
    encrypted_package_ref   VARCHAR(255),
    encryption_key_id       VARCHAR(255),
    generated_by            UUID,
    created_at              TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    version                 BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX idx_paper_tenant_id ON paper_generator.paper(tenant_id);
CREATE INDEX idx_paper_exam_id   ON paper_generator.paper(exam_id);
CREATE INDEX idx_paper_shift_id  ON paper_generator.paper(shift_id);
CREATE INDEX idx_paper_status    ON paper_generator.paper(status);

-- ============================================================
-- Table: blueprint_template
-- ============================================================
-- Stores reusable named blueprint rule-sets so Exam Controllers
-- can save a set of subject/topic/difficulty/cognitive rules once
-- and reuse them across multiple paper generation jobs.
--
-- rules_json is a JSONB array of BlueprintRule objects:
-- [{"subject":"Mathematics","topic":"Algebra","difficulty":"EASY",
--   "cognitiveLevel":"APPLY","questionCount":5}, ...]
CREATE TABLE paper_generator.blueprint_template (
    id           UUID         PRIMARY KEY,
    tenant_id    VARCHAR(255) NOT NULL,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(1000),
    exam_id      UUID,
    rules_json   JSONB        NOT NULL,
    created_by   UUID,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    version      BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uq_blueprint_template_tenant_name UNIQUE (tenant_id, name)
);

CREATE INDEX idx_blueprint_template_tenant_id ON paper_generator.blueprint_template(tenant_id);
CREATE INDEX idx_blueprint_template_exam_id   ON paper_generator.blueprint_template(exam_id);
