-- SPDX-License-Identifier: AGPL-3.0-only
--
-- National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
-- Copyright (C) 2025 NAG Contributors

CREATE SCHEMA IF NOT EXISTS paper_generator;

-- ============================================================
-- Table: paper
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
-- created_at / updated_at are set by BaseEntity @PrePersist / @PreUpdate;
-- no DEFAULT NOW() so the DB never silently overrides application values.
CREATE TABLE paper_generator.paper (
    id                      UUID         PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    exam_id                 UUID         NOT NULL,
    shift_id                VARCHAR(255) NOT NULL,
    status                  VARCHAR(20)  NOT NULL,
    paper_definition_json   JSONB,
    difficulty_score        DOUBLE PRECISION,
    topic_distribution_json JSONB,
    encrypted_package_ref   VARCHAR(255),
    encryption_key_id       VARCHAR(255),
    generated_by            UUID,
    created_at              TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    version                 BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX idx_paper_tenant_id ON paper_generator.paper(tenant_id);
CREATE INDEX idx_paper_exam_id   ON paper_generator.paper(exam_id);
CREATE INDEX idx_paper_shift_id  ON paper_generator.paper(shift_id);
CREATE INDEX idx_paper_status    ON paper_generator.paper(status);

-- ============================================================
-- Table: blueprint_template
-- ============================================================
-- Stores reusable named blueprint rule-sets so Exam Controllers
-- can save a set of subject/topic/difficulty/cognitive rules once
-- and reuse them across multiple paper generation jobs.
--
-- rules_json is a JSONB array of BlueprintRule objects:
-- [{"subject":"Mathematics","topic":"Algebra","difficulty":"EASY",
--   "cognitiveLevel":"APPLY","questionCount":5}, ...]
CREATE TABLE paper_generator.blueprint_template (
    id           UUID         PRIMARY KEY,
    tenant_id    VARCHAR(255) NOT NULL,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(1000),
    exam_id      UUID,
    rules_json   JSONB        NOT NULL,
    created_by   UUID,
    created_at   TIMESTAMP    NOT NULL,
    updated_at   TIMESTAMP    NOT NULL,
    version      BIGINT       NOT NULL DEFAULT 0,

    CONSTRAINT uq_blueprint_template_tenant_name UNIQUE (tenant_id, name)
);

CREATE INDEX idx_blueprint_template_tenant_id ON paper_generator.blueprint_template(tenant_id);
CREATE INDEX idx_blueprint_template_exam_id   ON paper_generator.blueprint_template(exam_id);

-- ============================================================
-- Seed Blueprint Rule Templates for Major Indian Government Examinations
-- ============================================================

INSERT INTO paper_generator.blueprint_template (
    id,
    tenant_id,
    name,
    description,
    exam_id,
    rules_json,
    created_by,
    created_at,
    updated_at,
    version
) VALUES
(
    'a1000000-0000-0000-0000-000000000001',
    'default',
    'SSC CGL Tier-1 (100 Questions - Standard)',
    'Official blueprint structure for Staff Selection Commission Combined Graduate Level (SSC CGL) Tier-1 CBT: 25 Qs Reasoning, 25 Qs General Awareness, 25 Qs Quantitative Aptitude, 25 Qs English Comprehension.',
    'e1000000-0000-0000-0000-000000000001',
    '[
        {"subject":"General Intelligence and Reasoning","topic":"Analogy","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":3},
        {"subject":"General Intelligence and Reasoning","topic":"Classification","difficulty":"EASY","cognitiveLevel":"REMEMBER","questionCount":3},
        {"subject":"General Intelligence and Reasoning","topic":"Series","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":3},
        {"subject":"General Intelligence and Reasoning","topic":"Coding and Decoding","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":3},
        {"subject":"General Intelligence and Reasoning","topic":"Venn Diagrams","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":2},
        {"subject":"General Intelligence and Reasoning","topic":"Problem Solving","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":3},
        {"subject":"General Intelligence and Reasoning","topic":"Critical Thinking","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":3},
        {"subject":"General Intelligence and Reasoning","topic":"Syllogistic Reasoning","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":3},
        {"subject":"General Intelligence and Reasoning","topic":"Numerical Operations","difficulty":"EASY","cognitiveLevel":"APPLY","questionCount":2},
        {"subject":"General Awareness","topic":"Current Events","difficulty":"MEDIUM","cognitiveLevel":"REMEMBER","questionCount":5},
        {"subject":"General Awareness","topic":"History","difficulty":"MEDIUM","cognitiveLevel":"REMEMBER","questionCount":4},
        {"subject":"General Awareness","topic":"Geography","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":4},
        {"subject":"General Awareness","topic":"Culture","difficulty":"EASY","cognitiveLevel":"REMEMBER","questionCount":3},
        {"subject":"General Awareness","topic":"Economic Scene","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":3},
        {"subject":"General Awareness","topic":"General Policy","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":3},
        {"subject":"General Awareness","topic":"Everyday Science","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":3},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Number Systems","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":3},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Fundamental Arithmetical Operations","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":7},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Algebra","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":3},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Geometry","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":4},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Mensuration","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":3},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Trigonometry","difficulty":"HARD","cognitiveLevel":"APPLY","questionCount":3},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Statistics and Probability","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":2},
        {"subject":"English Language and Comprehension","topic":"Spot the Error","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":3},
        {"subject":"English Language and Comprehension","topic":"Fill in the Blanks","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":2},
        {"subject":"English Language and Comprehension","topic":"Synonyms and Homonyms","difficulty":"MEDIUM","cognitiveLevel":"REMEMBER","questionCount":3},
        {"subject":"English Language and Comprehension","topic":"Antonyms","difficulty":"MEDIUM","cognitiveLevel":"REMEMBER","questionCount":3},
        {"subject":"English Language and Comprehension","topic":"Spellings","difficulty":"EASY","cognitiveLevel":"REMEMBER","questionCount":2},
        {"subject":"English Language and Comprehension","topic":"Idioms and Phrases","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":3},
        {"subject":"English Language and Comprehension","topic":"One Word Substitution","difficulty":"EASY","cognitiveLevel":"REMEMBER","questionCount":3},
        {"subject":"English Language and Comprehension","topic":"Improvement of Sentences","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":3},
        {"subject":"English Language and Comprehension","topic":"Cloze Passage","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":3}
    ]'::jsonb,
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'a1000000-0000-0000-0000-000000000002',
    'default',
    'Banking PO / Clerk Prelims (IBPS / SBI - 100 Qs)',
    'Standard blueprint for IBPS PO, SBI PO, and Regional Rural Banks (RRB) Preliminary Examination: English Language (30 Qs), Quantitative Aptitude (35 Qs), and Reasoning Ability (35 Qs).',
    'e1000000-0000-0000-0000-000000000002',
    '[
        {"subject":"English Language and Comprehension","topic":"Comprehension Passage","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":10},
        {"subject":"English Language and Comprehension","topic":"Spot the Error","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":5},
        {"subject":"English Language and Comprehension","topic":"Cloze Passage","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":5},
        {"subject":"English Language and Comprehension","topic":"Sentence Shuffling","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":5},
        {"subject":"English Language and Comprehension","topic":"Vocabulary","difficulty":"EASY","cognitiveLevel":"REMEMBER","questionCount":5},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Fundamental Arithmetical Operations","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":15},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Number Systems","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":5},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Statistics and Probability","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":10},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Algebra","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":5},
        {"subject":"General Intelligence and Reasoning","topic":"Syllogistic Reasoning","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":5},
        {"subject":"General Intelligence and Reasoning","topic":"Coding and Decoding","difficulty":"EASY","cognitiveLevel":"APPLY","questionCount":5},
        {"subject":"General Intelligence and Reasoning","topic":"Problem Solving","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":10},
        {"subject":"General Intelligence and Reasoning","topic":"Series","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":5},
        {"subject":"General Intelligence and Reasoning","topic":"Statement and Conclusion","difficulty":"HARD","cognitiveLevel":"EVALUATE","questionCount":5},
        {"subject":"General Intelligence and Reasoning","topic":"Drawing Inferences","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":5}
    ]'::jsonb,
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'a1000000-0000-0000-0000-000000000003',
    'default',
    'RRB NTPC CBT-1 (Railway Non-Technical - 100 Qs)',
    '100-question recruitment template for Railway Recruitment Board Non-Technical Popular Categories (General Awareness: 40 Qs, Mathematics: 30 Qs, General Intelligence & Reasoning: 30 Qs).',
    'e1000000-0000-0000-0000-000000000004',
    '[
        {"subject":"General Awareness","topic":"Current Events","difficulty":"MEDIUM","cognitiveLevel":"REMEMBER","questionCount":10},
        {"subject":"General Awareness","topic":"Everyday Science","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":10},
        {"subject":"General Awareness","topic":"History","difficulty":"MEDIUM","cognitiveLevel":"REMEMBER","questionCount":6},
        {"subject":"General Awareness","topic":"Geography","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":6},
        {"subject":"General Awareness","topic":"Economic Scene","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":4},
        {"subject":"General Awareness","topic":"India and Neighbouring Countries","difficulty":"MEDIUM","cognitiveLevel":"REMEMBER","questionCount":4},
        {"subject":"Mathematics","topic":"Arithmetic","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":12},
        {"subject":"Mathematics","topic":"Algebra","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":6},
        {"subject":"Mathematics","topic":"Geometry","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":4},
        {"subject":"Mathematics","topic":"Trigonometry","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":4},
        {"subject":"Mathematics","topic":"Statistics","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":4},
        {"subject":"General Intelligence and Reasoning","topic":"Analogy","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":5},
        {"subject":"General Intelligence and Reasoning","topic":"Coding and Decoding","difficulty":"EASY","cognitiveLevel":"APPLY","questionCount":5},
        {"subject":"General Intelligence and Reasoning","topic":"Series","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":5},
        {"subject":"General Intelligence and Reasoning","topic":"Venn Diagrams","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":5},
        {"subject":"General Intelligence and Reasoning","topic":"Problem Solving","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":5},
        {"subject":"General Intelligence and Reasoning","topic":"Statement and Conclusion","difficulty":"HARD","cognitiveLevel":"EVALUATE","questionCount":5}
    ]'::jsonb,
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'a1000000-0000-0000-0000-000000000004',
    'default',
    'UPSC CSE Prelims Paper-1 (General Studies - 100 Qs)',
    'Standard 100-question blueprint for Union Public Service Commission (UPSC) Civil Services Preliminary Examination GS Paper-1.',
    'e1000000-0000-0000-0000-000000000003',
    '[
        {"subject":"General Studies","topic":"Indian History","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":18},
        {"subject":"General Studies","topic":"Indian Polity","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":18},
        {"subject":"General Studies","topic":"Indian Geography","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":16},
        {"subject":"General Studies","topic":"Indian Economy","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":16},
        {"subject":"General Studies","topic":"Science & Technology","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":12},
        {"subject":"General Studies","topic":"Environment","difficulty":"HARD","cognitiveLevel":"EVALUATE","questionCount":12},
        {"subject":"General Studies","topic":"Current Affairs","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":8}
    ]'::jsonb,
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'a1000000-0000-0000-0000-000000000005',
    'default',
    'UPSC CSE Prelims Paper-2 (CSAT Aptitude - 80 Qs)',
    'Standard 80-question blueprint for UPSC Civil Services Examination Paper-2 (Civil Services Aptitude Test): Reading Comprehension (28 Qs), Reasoning (26 Qs), and Basic Numeracy/Data (26 Qs).',
    NULL,
    '[
        {"subject":"English Language and Comprehension","topic":"Comprehension Passage","difficulty":"HARD","cognitiveLevel":"EVALUATE","questionCount":28},
        {"subject":"General Intelligence and Reasoning","topic":"Critical Thinking","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":10},
        {"subject":"General Intelligence and Reasoning","topic":"Problem Solving","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":8},
        {"subject":"General Intelligence and Reasoning","topic":"Statement and Conclusion","difficulty":"HARD","cognitiveLevel":"EVALUATE","questionCount":8},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Fundamental Arithmetical Operations","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":14},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Number Systems","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":6},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Statistics and Probability","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":6}
    ]'::jsonb,
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'a1000000-0000-0000-0000-000000000006',
    'default',
    'SSC CGL Tier-2 (Paper-1 Core - 150 Qs)',
    'Comprehensive 150-question blueprint for SSC CGL Tier-2 CBT (Maths: 30, Reasoning: 30, English: 45, GA: 25, Computer Knowledge: 20).',
    NULL,
    '[
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Fundamental Arithmetical Operations","difficulty":"HARD","cognitiveLevel":"APPLY","questionCount":10},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Algebra","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":5},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Geometry","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":5},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Trigonometry","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":4},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Mensuration","difficulty":"HARD","cognitiveLevel":"APPLY","questionCount":4},
        {"subject":"Quantitative Aptitude / Mathematical Abilities","topic":"Statistics and Probability","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":2},
        {"subject":"General Intelligence and Reasoning","topic":"Problem Solving","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":8},
        {"subject":"General Intelligence and Reasoning","topic":"Critical Thinking","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":6},
        {"subject":"General Intelligence and Reasoning","topic":"Syllogistic Reasoning","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":4},
        {"subject":"General Intelligence and Reasoning","topic":"Analogy","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":4},
        {"subject":"General Intelligence and Reasoning","topic":"Statement and Conclusion","difficulty":"HARD","cognitiveLevel":"EVALUATE","questionCount":4},
        {"subject":"General Intelligence and Reasoning","topic":"Numerical Operations","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":4},
        {"subject":"English Language and Comprehension","topic":"Comprehension Passage","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":15},
        {"subject":"English Language and Comprehension","topic":"Cloze Passage","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":10},
        {"subject":"English Language and Comprehension","topic":"Active and Passive Voice","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":5},
        {"subject":"English Language and Comprehension","topic":"Direct and Indirect Narration","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":5},
        {"subject":"English Language and Comprehension","topic":"Spot the Error","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":5},
        {"subject":"English Language and Comprehension","topic":"Vocabulary","difficulty":"EASY","cognitiveLevel":"REMEMBER","questionCount":5},
        {"subject":"General Awareness","topic":"Current Events","difficulty":"MEDIUM","cognitiveLevel":"REMEMBER","questionCount":7},
        {"subject":"General Awareness","topic":"History","difficulty":"MEDIUM","cognitiveLevel":"REMEMBER","questionCount":4},
        {"subject":"General Awareness","topic":"Geography","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":4},
        {"subject":"General Awareness","topic":"Economic Scene","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":4},
        {"subject":"General Awareness","topic":"General Policy","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":3},
        {"subject":"General Awareness","topic":"Scientific Research","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":3},
        {"subject":"Computer Knowledge","topic":"Computer Basics","difficulty":"EASY","cognitiveLevel":"REMEMBER","questionCount":6},
        {"subject":"Computer Knowledge","topic":"Software","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":5},
        {"subject":"Computer Knowledge","topic":"Internet and E-mail","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":5},
        {"subject":"Computer Knowledge","topic":"Networking and Cyber Security","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":4}
    ]'::jsonb,
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'a1000000-0000-0000-0000-000000000007',
    'default',
    'State PSC Combined Prelims (General Studies - 150 Qs)',
    '150-question blueprint for State Public Service Commission (UPPSC, BPSC, MPPSC, MPSC, RPSC, TNPSC) Combined Competitive Preliminary Examination.',
    NULL,
    '[
        {"subject":"General Studies","topic":"Indian History","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":25},
        {"subject":"General Studies","topic":"Indian Geography","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":25},
        {"subject":"General Studies","topic":"Indian Polity","difficulty":"HARD","cognitiveLevel":"ANALYZE","questionCount":25},
        {"subject":"General Studies","topic":"Indian Economy","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":20},
        {"subject":"General Studies","topic":"Science & Technology","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":15},
        {"subject":"General Studies","topic":"Environment","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":15},
        {"subject":"General Studies","topic":"Current Affairs","difficulty":"MEDIUM","cognitiveLevel":"REMEMBER","questionCount":15},
        {"subject":"General Intelligence and Reasoning","topic":"Problem Solving","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":10}
    ]'::jsonb,
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'a1000000-0000-0000-0000-000000000008',
    'default',
    'CTET / TET Paper-1 (Primary Teacher - 150 Qs)',
    'Standard 150-question blueprint for Central Teacher Eligibility Test (CTET) and State TET Paper-1 (Child Development, English, Hindi, Mathematics, Environmental Studies).',
    'e1000000-0000-0000-0000-000000000005',
    '[
        {"subject":"Child Development and Pedagogy","topic":"Child Development & Learning Principles","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":15},
        {"subject":"Child Development and Pedagogy","topic":"Inclusive Education & Special Needs","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":8},
        {"subject":"Child Development and Pedagogy","topic":"Assessment, Evaluation & CCE","difficulty":"HARD","cognitiveLevel":"EVALUATE","questionCount":7},
        {"subject":"English Language and Comprehension","topic":"Comprehension Passage","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":15},
        {"subject":"English Language and Comprehension","topic":"Grammar","difficulty":"EASY","cognitiveLevel":"APPLY","questionCount":10},
        {"subject":"English Language and Comprehension","topic":"Vocabulary","difficulty":"EASY","cognitiveLevel":"REMEMBER","questionCount":5},
        {"subject":"General Hindi","topic":"अपठित गद्यांश","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":15},
        {"subject":"General Hindi","topic":"संधि एवं संधि विच्छेद","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":5},
        {"subject":"General Hindi","topic":"समास एवं समास विग्रह","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":5},
        {"subject":"General Hindi","topic":"वाक्य शुद्धि एवं त्रुटि पहचान","difficulty":"MEDIUM","cognitiveLevel":"ANALYZE","questionCount":5},
        {"subject":"Mathematics","topic":"Arithmetic","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":15},
        {"subject":"Mathematics","topic":"Geometry","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":8},
        {"subject":"Mathematics","topic":"Mensuration","difficulty":"MEDIUM","cognitiveLevel":"APPLY","questionCount":7},
        {"subject":"General Studies","topic":"Environment","difficulty":"MEDIUM","cognitiveLevel":"UNDERSTAND","questionCount":15},
        {"subject":"General Studies","topic":"Science & Technology","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":10},
        {"subject":"General Awareness","topic":"Everyday Science","difficulty":"EASY","cognitiveLevel":"UNDERSTAND","questionCount":5}
    ]'::jsonb,
    NULL,
    NOW(),
    NOW(),
    0
)
ON CONFLICT (tenant_id, name) DO NOTHING;
