# SPDX-License-Identifier: AGPL-3.0-only
#
# National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
# Copyright (C) 2025 NAG Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, version 3 of the License.

{{- if .Values.identityService.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "examination-platform.fullname" . }}-identity-service
  labels:
    app.kubernetes.io/name: identity-service
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: exam-platform
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.identityService.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.identityService.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    app.kubernetes.io/name: identity-service
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
