-- SPDX-License-Identifier: AGPL-3.0-only
--
-- National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
-- Copyright (C) 2025 NAG Contributors

CREATE SCHEMA IF NOT EXISTS candidate_service;

-- ============================================================
-- Table: candidate_profile
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
CREATE TABLE candidate_service.candidate_profile (
    id                      UUID PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    user_id                 UUID NOT NULL,
    full_name               VARCHAR(255),
    date_of_birth           VARCHAR(255),
    gender                  VARCHAR(255),
    nationality             VARCHAR(255),
    category                VARCHAR(255),
    mobile                  VARCHAR(255),
    email                   VARCHAR(255),
    address                 VARCHAR(255),
    reservation_category    VARCHAR(255),
    identity_doc_number     VARCHAR(255),
    mobile_hash             VARCHAR(64) NOT NULL,
    identity_doc_hash       VARCHAR(64) NOT NULL,
    identity_doc_hmac       VARCHAR(64) NOT NULL,
    encryption_key_id       VARCHAR(255),
    digi_locker_verified    VARCHAR(20),
    face_verification_status VARCHAR(20),
    consent_recorded        BOOLEAN NOT NULL DEFAULT FALSE,
    consent_timestamp       TIMESTAMP,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    version                 BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_candidate_profile_tenant_id ON candidate_service.candidate_profile(tenant_id);
CREATE INDEX idx_candidate_profile_user_id ON candidate_service.candidate_profile(user_id);
CREATE INDEX idx_candidate_profile_mobile_hash ON candidate_service.candidate_profile(mobile_hash);
CREATE INDEX idx_candidate_profile_identity_doc_hash ON candidate_service.candidate_profile(identity_doc_hash);
