-- SPDX-License-Identifier: AGPL-3.0-only
--
-- National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
-- Copyright (C) 2025 NAG Contributors

CREATE SCHEMA IF NOT EXISTS candidate_service;

-- ============================================================
-- Table: candidate_profile
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
CREATE TABLE candidate_service.candidate_profile (
    id                      UUID PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    user_id                 UUID NOT NULL,
    full_name               VARCHAR(255),
    date_of_birth           VARCHAR(255),
    gender                  VARCHAR(255),
    nationality             VARCHAR(255),
    category                VARCHAR(255),
    mobile                  VARCHAR(255),
    email                   VARCHAR(255),
    address                 VARCHAR(255),
    reservation_category    VARCHAR(255),
    identity_doc_number     VARCHAR(255),
    mobile_hash             VARCHAR(64) NOT NULL,
    identity_doc_hash       VARCHAR(64) NOT NULL,
    identity_doc_hmac       VARCHAR(64) NOT NULL,
    encryption_key_id       VARCHAR(255),
    digi_locker_verified    VARCHAR(20),
    face_verification_status VARCHAR(20),
    consent_recorded        BOOLEAN NOT NULL DEFAULT FALSE,
    consent_timestamp       TIMESTAMP,
    photo_asset_id          UUID,
    signature_asset_id      UUID,
    id_proof_asset_id       UUID,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    version                 BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_candidate_profile_tenant_id ON candidate_service.candidate_profile(tenant_id);
CREATE INDEX idx_candidate_profile_user_id ON candidate_service.candidate_profile(user_id);
CREATE INDEX idx_candidate_profile_mobile_hash ON candidate_service.candidate_profile(mobile_hash);
CREATE INDEX idx_candidate_profile_identity_doc_hash ON candidate_service.candidate_profile(identity_doc_hash);

-- ============================================================
-- Table: candidate_education
-- ============================================================
CREATE TABLE candidate_service.candidate_education (
    id                      UUID PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    user_id                 UUID NOT NULL,
    qualification           VARCHAR(50) NOT NULL,
    course_name             VARCHAR(255),
    board_or_university     VARCHAR(255) NOT NULL,
    institution_name        VARCHAR(255),
    passing_year            INTEGER NOT NULL,
    percentage_or_cgpa      NUMERIC(5, 2),
    grade_or_division       VARCHAR(50),
    specialization          VARCHAR(255),
    roll_number             VARCHAR(100),
    certificate_asset_id    UUID,
    created_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at              TIMESTAMP NOT NULL DEFAULT NOW(),
    version                 BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_candidate_education_tenant_id ON candidate_service.candidate_education(tenant_id);
CREATE INDEX idx_candidate_education_user_id ON candidate_service.candidate_education(user_id);
