-- SPDX-License-Identifier: AGPL-3.0-only
--
-- National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
-- Copyright (C) 2025 NAG Contributors

CREATE SCHEMA IF NOT EXISTS translation_service;

-- ============================================================
-- Table: translation
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
CREATE TABLE translation_service.translation (
    id                  UUID PRIMARY KEY,
    tenant_id           VARCHAR(255) NOT NULL,
    question_id         UUID NOT NULL,
    language_code       VARCHAR(10) NOT NULL,
    translated_content  TEXT,
    status              VARCHAR(20) NOT NULL,
    translator_id       UUID NOT NULL,
    reviewer_id         UUID,
    review_comments     TEXT,
    created_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMP NOT NULL DEFAULT NOW(),
    version             BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_translation_tenant_id ON translation_service.translation(tenant_id);
CREATE INDEX idx_translation_question_id ON translation_service.translation(question_id);
CREATE INDEX idx_translation_language_code ON translation_service.translation(language_code);
CREATE INDEX idx_translation_status ON translation_service.translation(status);
