# SPDX-License-Identifier: AGPL-3.0-only
#
# National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
# Copyright (C) 2025 NAG Contributors
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published
# by the Free Software Foundation, version 3 of the License.

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/exam_platform
    username: exam_admin
    password: exam_secret
    hikari:
      schema: asset_service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/exam-realm
          jwk-set-uri: http://keycloak:8080/realms/exam-realm/protocol/openid-connect/certs

  kafka:
    bootstrap-servers: kafka:9092

otel:
  exporter:
    otlp:
      endpoint: http://otel-collector:4317

asset:
  storage:
    provider: filesystem
    filesystem:
      base-path: /data/asset-storage
