export type SchedulingTab = 'SCHEDULES' | 'SHIFTS' | 'ALLOCATIONS';

export const SCHEDULE_STATUS_TRANSITIONS: Record<string, string[]> = {
  DRAFT: ['SCHEDULER_REVIEW', 'CANCELLED'],
  SCHEDULER_REVIEW: ['CONTROLLER_APPROVED', 'CANCELLED'],
  CONTROLLER_APPROVED: ['SECURITY_REVIEW', 'CANCELLED'],
  SECURITY_REVIEW: ['CHAIRMAN_APPROVED', 'CANCELLED'],
  CHAIRMAN_APPROVED: ['PUBLISHED', 'CANCELLED'],
  PUBLISHED: ['CANCELLED'],
};
