CREATE SCHEMA IF NOT EXISTS examination_service;

-- ============================================================
-- Table: examination
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
CREATE TABLE examination_service.examination (
    id                          UUID PRIMARY KEY,
    tenant_id                   VARCHAR(255) NOT NULL,
    name                        VARCHAR(500) NOT NULL,
    duration_minutes            INTEGER NOT NULL,
    total_marks                 INTEGER NOT NULL,
    negative_marking_enabled    BOOLEAN NOT NULL DEFAULT FALSE,
    negative_marking_value      DOUBLE PRECISION,
    navigation_policy           VARCHAR(20) NOT NULL,
    calculator_policy           VARCHAR(20) NOT NULL,
    review_flag_enabled         BOOLEAN NOT NULL DEFAULT FALSE,
    sections_json               JSONB,
    status                      VARCHAR(20) NOT NULL,
    created_at                  TIMESTAMP NOT NULL DEFAULT NOW(),
    updated_at                  TIMESTAMP NOT NULL DEFAULT NOW(),
    version                     BIGINT NOT NULL DEFAULT 0
);

CREATE INDEX idx_examination_tenant_id ON examination_service.examination(tenant_id);
CREATE INDEX idx_examination_status ON examination_service.examination(status);
