-- SPDX-License-Identifier: AGPL-3.0-only
--
-- National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
-- Copyright (C) 2025 NAG Contributors

CREATE SCHEMA IF NOT EXISTS examination_service;

-- ============================================================
-- Table: examination
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
-- created_at / updated_at are set by BaseEntity @PrePersist / @PreUpdate.
CREATE TABLE examination_service.examination (
    id                          UUID         PRIMARY KEY,
    tenant_id                   VARCHAR(255) NOT NULL,

    -- Core identity
    name                        VARCHAR(500) NOT NULL,
    code                        VARCHAR(100),                  -- unique examination code per tenant
    conducting_authority        VARCHAR(255),
    category                    VARCHAR(30),                   -- RECRUITMENT / ENTRANCE / CERTIFICATION / DEPARTMENTAL
    examination_type            VARCHAR(30),                   -- PRELIMINARY / MAIN / SKILL_TEST / INTERVIEW / PHYSICAL_TEST
    academic_year               VARCHAR(20),                   -- e.g. "2026-27"
    examination_mode            VARCHAR(20),                   -- CBT / OMR / HYBRID

    -- Exam configuration
    duration_minutes            INTEGER      NOT NULL,
    total_marks                 INTEGER      NOT NULL,
    negative_marking_enabled    BOOLEAN      NOT NULL DEFAULT FALSE,
    negative_marking_value      DOUBLE PRECISION,
    navigation_policy           VARCHAR(20)  NOT NULL,
    calculator_policy           VARCHAR(20)  NOT NULL,
    review_flag_enabled         BOOLEAN      NOT NULL DEFAULT FALSE,
    sections_json               JSONB,

    -- Status
    status                      VARCHAR(30)  NOT NULL,         -- DRAFT / APPROVED / PUBLISHED / CANCELLED / COMPLETED

    -- Audit
    created_by                  UUID,
    created_at                  TIMESTAMP    NOT NULL,
    updated_at                  TIMESTAMP    NOT NULL,
    version                     BIGINT       NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uq_examination_tenant_code
    ON examination_service.examination(tenant_id, code)
    WHERE code IS NOT NULL;

CREATE INDEX idx_examination_tenant_id ON examination_service.examination(tenant_id);
CREATE INDEX idx_examination_status    ON examination_service.examination(status);

-- ============================================================
-- Table: examination_schedule
-- ============================================================
-- One examination may have multiple schedules (e.g. multi-phase).
-- Each amendment creates a new row with an incremented version and a
-- previous_version_id pointer, forming an immutable version chain.
CREATE TABLE examination_service.examination_schedule (
    id                      UUID         PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    examination_id          UUID         NOT NULL
                                REFERENCES examination_service.examination(id),

    schedule_name           VARCHAR(255) NOT NULL,
    schedule_version        INTEGER      NOT NULL DEFAULT 1,   -- business version (1, 2, 3…); distinct from OL lock
    notification_number     VARCHAR(100),                      -- government notification reference
    exam_date               DATE         NOT NULL,
    reserve_date            DATE,                              -- backup date; validated for conflicts
    time_zone               VARCHAR(60)  NOT NULL DEFAULT 'Asia/Kolkata',

    -- Approval workflow state
    -- DRAFT → SCHEDULER_REVIEW → CONTROLLER_APPROVED → SECURITY_REVIEW → CHAIRMAN_APPROVED → PUBLISHED / CANCELLED
    status                  VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',

    -- Amendment fields
    change_reason           VARCHAR(1000),                     -- mandatory on amendments to Published schedules
    effective_from          DATE,

    -- Version chain
    previous_version_id     UUID
                                REFERENCES examination_service.examination_schedule(id),

    -- Ownership / approval tracking
    created_by              UUID,
    modified_by             UUID,
    approved_by             UUID,
    approved_at             TIMESTAMP,

    -- BaseEntity columns
    created_at              TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    version                 BIGINT       NOT NULL DEFAULT 0    -- JPA optimistic-lock counter
);

CREATE INDEX idx_schedule_examination_id ON examination_service.examination_schedule(examination_id);
CREATE INDEX idx_schedule_tenant_id      ON examination_service.examination_schedule(tenant_id);
CREATE INDEX idx_schedule_exam_date      ON examination_service.examination_schedule(exam_date);
CREATE INDEX idx_schedule_status         ON examination_service.examination_schedule(status);

-- ============================================================
-- Table: exam_shift
-- ============================================================
-- Each schedule date may have multiple shifts.
-- All time fields store local time (no date component); the schedule's
-- exam_date + time_zone is the authoritative combined instant.
-- Constraints are enforced at the application layer with descriptive errors;
-- the CHECK constraints here provide a DB-level backstop.
CREATE TABLE examination_service.exam_shift (
    id                  UUID        PRIMARY KEY,
    tenant_id           VARCHAR(255) NOT NULL,
    schedule_id         UUID        NOT NULL
                            REFERENCES examination_service.examination_schedule(id),

    shift_number        INTEGER     NOT NULL,                  -- 1, 2, 3...
    shift_name          VARCHAR(100),                          -- "Morning" / "Afternoon" / "Evening"

    reporting_time      TIME        NOT NULL,
    gate_closing_time   TIME        NOT NULL,
    login_start_time    TIME        NOT NULL,
    exam_start_time     TIME        NOT NULL,
    exam_end_time       TIME        NOT NULL,
    exit_time           TIME,
    duration_minutes    INTEGER     NOT NULL,
    buffer_minutes      INTEGER     NOT NULL DEFAULT 0,

    -- DB-level backstop for timing ordering
    CONSTRAINT chk_shift_reporting_before_gate
        CHECK (reporting_time < gate_closing_time),
    CONSTRAINT chk_shift_gate_before_login
        CHECK (gate_closing_time < login_start_time),
    CONSTRAINT chk_shift_login_before_start
        CHECK (login_start_time < exam_start_time),
    CONSTRAINT chk_shift_start_before_end
        CHECK (exam_start_time < exam_end_time),

    -- BaseEntity columns
    created_at          TIMESTAMP   NOT NULL,
    updated_at          TIMESTAMP   NOT NULL,
    version             BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uq_exam_shift_schedule_number UNIQUE (schedule_id, shift_number)
);

CREATE INDEX idx_exam_shift_schedule_id ON examination_service.exam_shift(schedule_id);

-- ============================================================
-- Table: examination_centre
-- ============================================================
CREATE TABLE examination_service.examination_centre (
    id                      UUID         PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,

    region                  VARCHAR(100),
    state                   VARCHAR(100) NOT NULL,
    district                VARCHAR(100),
    city                    VARCHAR(100) NOT NULL,
    centre_name             VARCHAR(255) NOT NULL,
    building                VARCHAR(255),
    floor                   VARCHAR(50),
    laboratory_identifier   VARCHAR(100),
    total_capacity          INTEGER      NOT NULL DEFAULT 0,
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,

    -- BaseEntity columns
    created_at              TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    version                 BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX idx_centre_tenant_id ON examination_service.examination_centre(tenant_id);
CREATE INDEX idx_centre_state     ON examination_service.examination_centre(state);
CREATE INDEX idx_centre_city      ON examination_service.examination_centre(city);

-- ============================================================
-- Table: shift_seat_allocation
-- ============================================================
-- Seat allocation per (shift, centre) pair.
-- available_seats must never go below zero (enforced at application layer;
-- the CHECK here provides a DB backstop).
CREATE TABLE examination_service.shift_seat_allocation (
    id                      UUID        PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    shift_id                UUID        NOT NULL
                                REFERENCES examination_service.exam_shift(id),
    centre_id               UUID        NOT NULL
                                REFERENCES examination_service.examination_centre(id),

    total_seats             INTEGER     NOT NULL DEFAULT 0,
    available_seats         INTEGER     NOT NULL DEFAULT 0,
    reserved_seats          INTEGER     NOT NULL DEFAULT 0,
    pwd_seats               INTEGER     NOT NULL DEFAULT 0,    -- Persons with Disabilities
    emergency_buffer_seats  INTEGER     NOT NULL DEFAULT 0,
    female_reserved_seats   INTEGER     NOT NULL DEFAULT 0,
    special_category_seats  INTEGER     NOT NULL DEFAULT 0,

    CONSTRAINT chk_allocation_available_non_negative
        CHECK (available_seats >= 0),

    -- BaseEntity columns
    created_at              TIMESTAMP   NOT NULL,
    updated_at              TIMESTAMP   NOT NULL,
    version                 BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uq_allocation_shift_centre UNIQUE (shift_id, centre_id)
);

CREATE INDEX idx_allocation_shift_id  ON examination_service.shift_seat_allocation(shift_id);
CREATE INDEX idx_allocation_centre_id ON examination_service.shift_seat_allocation(centre_id);
