-- SPDX-License-Identifier: AGPL-3.0-only
--
-- National Assessment Grid (NAG) - Open Digital Public Infrastructure (DPI) Platform
-- Copyright (C) 2025 NAG Contributors

CREATE SCHEMA IF NOT EXISTS examination_service;

-- ============================================================
-- Table: examination
-- ============================================================
-- IDs are UUID v7, generated by the application (UuidV7Generator) before insert.
-- No DEFAULT gen_random_uuid() — the database never assigns IDs.
-- created_at / updated_at are set by BaseEntity @PrePersist / @PreUpdate.
CREATE TABLE examination_service.examination (
    id                          UUID         PRIMARY KEY,
    tenant_id                   VARCHAR(255) NOT NULL,

    -- Core identity
    name                        VARCHAR(500) NOT NULL,
    code                        VARCHAR(100),                  -- unique examination code per tenant
    conducting_authority        VARCHAR(255),
    category                    VARCHAR(30),                   -- RECRUITMENT / ENTRANCE / CERTIFICATION / DEPARTMENTAL
    examination_type            VARCHAR(30),                   -- PRELIMINARY / MAIN / SKILL_TEST / INTERVIEW / PHYSICAL_TEST
    academic_year               VARCHAR(20),                   -- e.g. "2026-27"
    examination_mode            VARCHAR(20),                   -- CBT / OMR / HYBRID

    -- Exam configuration
    duration_minutes            INTEGER      NOT NULL,
    total_marks                 INTEGER      NOT NULL,
    negative_marking_enabled    BOOLEAN      NOT NULL DEFAULT FALSE,
    negative_marking_value      DOUBLE PRECISION,
    navigation_policy           VARCHAR(20)  NOT NULL,
    calculator_policy           VARCHAR(20)  NOT NULL,
    review_flag_enabled         BOOLEAN      NOT NULL DEFAULT FALSE,
    sections_json               JSONB,

    -- Status
    status                      VARCHAR(30)  NOT NULL,         -- DRAFT / APPROVED / PUBLISHED / CANCELLED / COMPLETED

    -- Audit
    created_by                  UUID,
    created_at                  TIMESTAMP    NOT NULL,
    updated_at                  TIMESTAMP    NOT NULL,
    version                     BIGINT       NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX uq_examination_tenant_code
    ON examination_service.examination(tenant_id, code)
    WHERE code IS NOT NULL;

CREATE INDEX idx_examination_tenant_id ON examination_service.examination(tenant_id);
CREATE INDEX idx_examination_status    ON examination_service.examination(status);

-- ============================================================
-- Table: examination_schedule
-- ============================================================
-- One examination may have multiple schedules (e.g. multi-phase).
-- Each amendment creates a new row with an incremented version and a
-- previous_version_id pointer, forming an immutable version chain.
CREATE TABLE examination_service.examination_schedule (
    id                      UUID         PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    examination_id          UUID         NOT NULL
                                REFERENCES examination_service.examination(id),

    schedule_name           VARCHAR(255) NOT NULL,
    schedule_version        INTEGER      NOT NULL DEFAULT 1,   -- business version (1, 2, 3…); distinct from OL lock
    notification_number     VARCHAR(100),                      -- government notification reference
    exam_date               DATE         NOT NULL,
    reserve_date            DATE,                              -- backup date; validated for conflicts
    time_zone               VARCHAR(60)  NOT NULL DEFAULT 'Asia/Kolkata',

    -- Approval workflow state
    -- DRAFT → SCHEDULER_REVIEW → CONTROLLER_APPROVED → SECURITY_REVIEW → CHAIRMAN_APPROVED → PUBLISHED / CANCELLED
    status                  VARCHAR(30)  NOT NULL DEFAULT 'DRAFT',

    -- Amendment fields
    change_reason           VARCHAR(1000),                     -- mandatory on amendments to Published schedules
    effective_from          DATE,

    -- Version chain
    previous_version_id     UUID
                                REFERENCES examination_service.examination_schedule(id),

    -- Ownership / approval tracking
    created_by              UUID,
    modified_by             UUID,
    approved_by             UUID,
    approved_at             TIMESTAMP,

    -- BaseEntity columns
    created_at              TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    version                 BIGINT       NOT NULL DEFAULT 0    -- JPA optimistic-lock counter
);

CREATE INDEX idx_schedule_examination_id ON examination_service.examination_schedule(examination_id);
CREATE INDEX idx_schedule_tenant_id      ON examination_service.examination_schedule(tenant_id);
CREATE INDEX idx_schedule_exam_date      ON examination_service.examination_schedule(exam_date);
CREATE INDEX idx_schedule_status         ON examination_service.examination_schedule(status);

-- ============================================================
-- Table: exam_shift
-- ============================================================
-- Each schedule date may have multiple shifts.
-- All time fields store local time (no date component); the schedule's
-- exam_date + time_zone is the authoritative combined instant.
-- Constraints are enforced at the application layer with descriptive errors;
-- the CHECK constraints here provide a DB-level backstop.
CREATE TABLE examination_service.exam_shift (
    id                  UUID        PRIMARY KEY,
    tenant_id           VARCHAR(255) NOT NULL,
    schedule_id         UUID        NOT NULL
                            REFERENCES examination_service.examination_schedule(id),

    shift_number        INTEGER     NOT NULL,                  -- 1, 2, 3...
    shift_name          VARCHAR(100),                          -- "Morning" / "Afternoon" / "Evening"

    reporting_time      TIME        NOT NULL,
    gate_closing_time   TIME        NOT NULL,
    login_start_time    TIME        NOT NULL,
    exam_start_time     TIME        NOT NULL,
    exam_end_time       TIME        NOT NULL,
    exit_time           TIME,
    duration_minutes    INTEGER     NOT NULL,
    buffer_minutes      INTEGER     NOT NULL DEFAULT 0,

    -- DB-level backstop for timing ordering
    CONSTRAINT chk_shift_reporting_before_gate
        CHECK (reporting_time < gate_closing_time),
    CONSTRAINT chk_shift_gate_before_login
        CHECK (gate_closing_time < login_start_time),
    CONSTRAINT chk_shift_login_before_start
        CHECK (login_start_time < exam_start_time),
    CONSTRAINT chk_shift_start_before_end
        CHECK (exam_start_time < exam_end_time),

    -- BaseEntity columns
    created_at          TIMESTAMP   NOT NULL,
    updated_at          TIMESTAMP   NOT NULL,
    version             BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uq_exam_shift_schedule_number UNIQUE (schedule_id, shift_number)
);

CREATE INDEX idx_exam_shift_schedule_id ON examination_service.exam_shift(schedule_id);

-- ============================================================
-- Table: examination_centre
-- ============================================================
CREATE TABLE examination_service.examination_centre (
    id                      UUID         PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,

    region                  VARCHAR(100),
    state                   VARCHAR(100) NOT NULL,
    district                VARCHAR(100),
    city                    VARCHAR(100) NOT NULL,
    centre_name             VARCHAR(255) NOT NULL,
    building                VARCHAR(255),
    floor                   VARCHAR(50),
    laboratory_identifier   VARCHAR(100),
    total_capacity          INTEGER      NOT NULL DEFAULT 0,
    active                  BOOLEAN      NOT NULL DEFAULT TRUE,

    -- BaseEntity columns
    created_at              TIMESTAMP    NOT NULL,
    updated_at              TIMESTAMP    NOT NULL,
    version                 BIGINT       NOT NULL DEFAULT 0
);

CREATE INDEX idx_centre_tenant_id ON examination_service.examination_centre(tenant_id);
CREATE INDEX idx_centre_state     ON examination_service.examination_centre(state);
CREATE INDEX idx_centre_city      ON examination_service.examination_centre(city);

-- ============================================================
-- Table: shift_seat_allocation
-- ============================================================
-- Seat allocation per (shift, centre) pair.
-- available_seats must never go below zero (enforced at application layer;
-- the CHECK here provides a DB backstop).
CREATE TABLE examination_service.shift_seat_allocation (
    id                      UUID        PRIMARY KEY,
    tenant_id               VARCHAR(255) NOT NULL,
    shift_id                UUID        NOT NULL
                                REFERENCES examination_service.exam_shift(id),
    centre_id               UUID        NOT NULL
                                REFERENCES examination_service.examination_centre(id),

    total_seats             INTEGER     NOT NULL DEFAULT 0,
    available_seats         INTEGER     NOT NULL DEFAULT 0,
    reserved_seats          INTEGER     NOT NULL DEFAULT 0,
    pwd_seats               INTEGER     NOT NULL DEFAULT 0,    -- Persons with Disabilities
    emergency_buffer_seats  INTEGER     NOT NULL DEFAULT 0,
    female_reserved_seats   INTEGER     NOT NULL DEFAULT 0,
    special_category_seats  INTEGER     NOT NULL DEFAULT 0,

    CONSTRAINT chk_allocation_available_non_negative
        CHECK (available_seats >= 0),

    -- BaseEntity columns
    created_at              TIMESTAMP   NOT NULL,
    updated_at              TIMESTAMP   NOT NULL,
    version                 BIGINT      NOT NULL DEFAULT 0,

    CONSTRAINT uq_allocation_shift_centre UNIQUE (shift_id, centre_id)
);

CREATE INDEX idx_allocation_shift_id  ON examination_service.shift_seat_allocation(shift_id);
CREATE INDEX idx_allocation_centre_id ON examination_service.shift_seat_allocation(centre_id);

-- ============================================================
-- Table: exam_application
-- Tracks candidate applications to examinations.
-- ============================================================
CREATE TABLE IF NOT EXISTS examination_service.exam_application
(
    id                  UUID         NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
    candidate_id        UUID         NOT NULL,
    examination_id      UUID         NOT NULL REFERENCES examination_service.examination (id) ON DELETE CASCADE,
    tenant_id           VARCHAR(100) NOT NULL,
    status              VARCHAR(20)  NOT NULL DEFAULT 'APPLIED',
    hall_ticket_number  VARCHAR(30),
    applied_at          TIMESTAMP    NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_candidate_exam_tenant UNIQUE (candidate_id, examination_id, tenant_id),
    CONSTRAINT chk_application_status CHECK (status IN ('APPLIED', 'CONFIRMED', 'REJECTED'))
);

CREATE INDEX idx_exam_application_candidate ON examination_service.exam_application (candidate_id, tenant_id);
CREATE INDEX idx_exam_application_exam ON examination_service.exam_application (examination_id, tenant_id);

COMMENT ON TABLE examination_service.exam_application IS
    'Tracks candidate applications to examinations. Unique per (candidate, exam, tenant).';

-- ============================================================
-- Geo-location lookup tables: country -> state -> city
-- ============================================================
-- These tables provide cascading dropdown data for the UI.

-- ── Country ───────────────────────────────────────────────────
CREATE TABLE examination_service.geo_country (
    id          BIGINT       PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    iso2        VARCHAR(2),
    iso3        VARCHAR(3),
    phone_code  VARCHAR(20),
    capital     VARCHAR(100),
    currency    VARCHAR(50),
    region      VARCHAR(100),
    subregion   VARCHAR(100),
    active      BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_geo_country_name ON examination_service.geo_country(name);

-- ── State ─────────────────────────────────────────────────────
CREATE TABLE examination_service.geo_state (
    id           BIGINT       PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    country_id   BIGINT       NOT NULL REFERENCES examination_service.geo_country(id),
    state_code   VARCHAR(10),
    type         VARCHAR(50),   -- "state" / "union territory"
    active       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_geo_state_country ON examination_service.geo_state(country_id);
CREATE INDEX idx_geo_state_name    ON examination_service.geo_state(name);

-- ── City ──────────────────────────────────────────────────────
CREATE TABLE examination_service.geo_city (
    id           BIGINT       PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    state_id     BIGINT       NOT NULL REFERENCES examination_service.geo_state(id),
    country_id   BIGINT       NOT NULL REFERENCES examination_service.geo_country(id),
    latitude     NUMERIC(10,8),
    longitude    NUMERIC(11,8),
    active       BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_geo_city_state   ON examination_service.geo_city(state_id);
CREATE INDEX idx_geo_city_country ON examination_service.geo_city(country_id);
CREATE INDEX idx_geo_city_name    ON examination_service.geo_city(name);

-- ── Update examination_centre to use geo FK IDs ───────────────
ALTER TABLE examination_service.examination_centre
    ADD COLUMN country_id BIGINT REFERENCES examination_service.geo_country(id),
    ADD COLUMN state_id   BIGINT REFERENCES examination_service.geo_state(id),
    ADD COLUMN city_id    BIGINT REFERENCES examination_service.geo_city(id);

-- ════════════════════════════════════════════════════════════════
-- SEED DATA: India + 28 states/8 UTs + major cities
-- ════════════════════════════════════════════════════════════════

-- Country: India
INSERT INTO examination_service.geo_country (id, name, iso2, iso3, phone_code, capital, currency, region, subregion)
VALUES (101, 'India', 'IN', 'IND', '91', 'New Delhi', 'INR', 'Asia', 'Southern Asia')
ON CONFLICT (id) DO NOTHING;

-- States & Union Territories
INSERT INTO examination_service.geo_state (id, name, country_id, state_code, type) VALUES
(4023, 'Andhra Pradesh',       101, 'AP', 'state'),
(4024, 'Arunachal Pradesh',    101, 'AR', 'state'),
(4025, 'Assam',                101, 'AS', 'state'),
(4026, 'Bihar',                101, 'BR', 'state'),
(4027, 'Chhattisgarh',         101, 'CG', 'state'),
(4028, 'Goa',                  101, 'GA', 'state'),
(4029, 'Gujarat',              101, 'GJ', 'state'),
(4030, 'Haryana',              101, 'HR', 'state'),
(4031, 'Himachal Pradesh',     101, 'HP', 'state'),
(4032, 'Jharkhand',            101, 'JH', 'state'),
(4033, 'Karnataka',            101, 'KA', 'state'),
(4034, 'Kerala',               101, 'KL', 'state'),
(4035, 'Madhya Pradesh',       101, 'MP', 'state'),
(4036, 'Maharashtra',          101, 'MH', 'state'),
(4037, 'Manipur',              101, 'MN', 'state'),
(4038, 'Meghalaya',            101, 'ML', 'state'),
(4039, 'Mizoram',              101, 'MZ', 'state'),
(4040, 'Nagaland',             101, 'NL', 'state'),
(4041, 'Odisha',               101, 'OD', 'state'),
(4042, 'Punjab',               101, 'PB', 'state'),
(4043, 'Rajasthan',            101, 'RJ', 'state'),
(4044, 'Sikkim',               101, 'SK', 'state'),
(4045, 'Tamil Nadu',           101, 'TN', 'state'),
(4046, 'Telangana',            101, 'TS', 'state'),
(4047, 'Tripura',              101, 'TR', 'state'),
(4048, 'Uttar Pradesh',        101, 'UP', 'state'),
(4049, 'Uttarakhand',          101, 'UK', 'state'),
(4050, 'West Bengal',          101, 'WB', 'state'),
-- Union Territories
(4051, 'Delhi',                         101, 'DL', 'union territory'),
(4052, 'Jammu and Kashmir',             101, 'JK', 'union territory'),
(4053, 'Ladakh',                        101, 'LA', 'union territory'),
(4054, 'Chandigarh',                    101, 'CH', 'union territory'),
(4055, 'Puducherry',                    101, 'PY', 'union territory'),
(4056, 'Andaman and Nicobar Islands',   101, 'AN', 'union territory'),
(4057, 'Dadra and Nagar Haveli and Daman and Diu', 101, 'DD', 'union territory'),
(4058, 'Lakshadweep',                   101, 'LD', 'union territory')
ON CONFLICT (id) DO NOTHING;

-- Cities (major cities for dev/testing)
INSERT INTO examination_service.geo_city (id, name, state_id, country_id, latitude, longitude) VALUES
-- Delhi
(50001, 'New Delhi',       4051, 101, 28.61390000, 77.20900000),
-- Maharashtra
(50002, 'Mumbai',          4036, 101, 19.07600000, 72.87770000),
(50003, 'Pune',            4036, 101, 18.52040000, 73.85670000),
(50004, 'Nagpur',          4036, 101, 21.14660000, 79.08880000),
(50005, 'Nashik',          4036, 101, 19.99740000, 73.79050000),
-- Karnataka
(50006, 'Bengaluru',       4033, 101, 12.97160000, 77.59460000),
(50007, 'Mysuru',          4033, 101, 12.29580000, 76.63940000),
(50008, 'Hubli',           4033, 101, 15.36470000, 75.12400000),
-- Tamil Nadu
(50009, 'Chennai',         4045, 101, 13.08250000, 80.27500000),
(50010, 'Coimbatore',      4045, 101, 11.01680000, 76.95580000),
(50011, 'Madurai',         4045, 101, 9.93920000,  78.12770000),
-- Telangana
(50012, 'Hyderabad',       4046, 101, 17.38500000, 78.48670000),
(50013, 'Warangal',        4046, 101, 17.97840000, 79.60000000),
-- Kerala
(50014, 'Thiruvananthapuram', 4034, 101, 8.52410000,  76.93610000),
(50015, 'Kochi',           4034, 101, 9.93120000,  76.26730000),
-- Gujarat
(50016, 'Ahmedabad',       4029, 101, 23.02250000, 72.57140000),
(50017, 'Surat',           4029, 101, 21.17020000, 72.83110000),
(50018, 'Vadodara',        4029, 101, 22.30720000, 73.18120000),
-- Rajasthan
(50019, 'Jaipur',          4043, 101, 26.91240000, 75.78730000),
(50020, 'Jodhpur',         4043, 101, 26.28930000, 73.02440000),
(50021, 'Udaipur',         4043, 101, 24.58540000, 73.71250000),
-- Uttar Pradesh
(50022, 'Lucknow',         4048, 101, 26.84670000, 80.94620000),
(50023, 'Noida',           4048, 101, 28.53550000, 77.39100000),
(50024, 'Varanasi',        4048, 101, 25.31760000, 82.98740000),
(50025, 'Agra',            4048, 101, 27.17670000, 78.00810000),
(50026, 'Kanpur',          4048, 101, 26.44990000, 80.33190000),
(50027, 'Prayagraj',       4048, 101, 25.43580000, 81.84630000),
-- Madhya Pradesh
(50028, 'Bhopal',          4035, 101, 23.25990000, 77.41260000),
(50029, 'Indore',          4035, 101, 22.71960000, 75.85770000),
-- Bihar
(50030, 'Patna',           4026, 101, 25.61000000, 85.14140000),
-- West Bengal
(50031, 'Kolkata',         4050, 101, 22.57260000, 88.36390000),
(50032, 'Siliguri',        4050, 101, 26.72710000, 88.39530000),
-- Punjab
(50033, 'Chandigarh',      4054, 101, 30.73330000, 76.77940000),
(50034, 'Ludhiana',        4042, 101, 30.90100000, 75.85730000),
(50035, 'Amritsar',        4042, 101, 31.63400000, 74.87230000),
-- Haryana
(50036, 'Gurugram',        4030, 101, 28.45950000, 77.02660000),
(50037, 'Faridabad',       4030, 101, 28.40890000, 77.31780000),
-- Jharkhand
(50038, 'Ranchi',          4032, 101, 23.34410000, 85.30960000),
(50039, 'Jamshedpur',      4032, 101, 22.80460000, 86.20290000),
-- Chhattisgarh
(50040, 'Raipur',          4027, 101, 21.25140000, 81.62960000),
-- Odisha
(50041, 'Bhubaneswar',     4041, 101, 20.29610000, 85.82450000),
-- Andhra Pradesh
(50042, 'Visakhapatnam',   4023, 101, 17.68680000, 83.21850000),
(50043, 'Vijayawada',      4023, 101, 16.50620000, 80.64800000),
(50044, 'Tirupati',        4023, 101, 13.63880000, 79.42060000),
-- Assam
(50045, 'Guwahati',        4025, 101, 26.14450000, 91.73620000),
-- Uttarakhand
(50046, 'Dehradun',        4049, 101, 30.31650000, 78.03220000),
-- Goa
(50047, 'Panaji',          4028, 101, 15.49900000, 73.82780000)
ON CONFLICT (id) DO NOTHING;

-- ════════════════════════════════════════════════════════════════
-- SEED DATA: Initial Major Examination Centres across India
-- ════════════════════════════════════════════════════════════════
INSERT INTO examination_service.examination_centre (
    id,
    tenant_id,
    region,
    state,
    district,
    city,
    centre_name,
    building,
    floor,
    laboratory_identifier,
    total_capacity,
    active,
    created_at,
    updated_at,
    version,
    country_id,
    state_id,
    city_id
) VALUES
-- North Region (Delhi NCR, UP, Haryana, Punjab, Rajasthan)
(
    'c1000000-0000-0000-0000-000000000001',
    'default',
    'North',
    'Uttar Pradesh',
    'Gautam Buddha Nagar',
    'Noida',
    'iON Digital Zone iDZ 1 Sector 62',
    'C-56/28, Institutional Area, Sector 62',
    'Ground & 1st Floor',
    'LAB-A, LAB-B, LAB-C',
    600,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4048,
    50023
),
(
    'c1000000-0000-0000-0000-000000000002',
    'default',
    'North',
    'Delhi',
    'South West Delhi',
    'New Delhi',
    'National Assessment Centre Dwarka',
    'Sector 8 Institutional Area, Dwarka',
    '2nd Floor',
    'LAB-01, LAB-02',
    550,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4051,
    50001
),
(
    'c1000000-0000-0000-0000-000000000003',
    'default',
    'North',
    'Delhi',
    'North Delhi',
    'New Delhi',
    'iON Digital Zone iDZ GT Karnal Road',
    'Industrial Area, Near Azadpur Metro',
    '1st Floor',
    'LAB-NORTH-1',
    500,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4051,
    50001
),
(
    'c1000000-0000-0000-0000-000000000004',
    'default',
    'North',
    'Haryana',
    'Gurugram',
    'Gurugram',
    'Cyber City Testing Hub Sector 34',
    'Plot 12, Info Technology Park, Sector 34',
    '3rd Floor',
    'CYBER-LAB-A',
    450,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4030,
    50036
),
(
    'c1000000-0000-0000-0000-000000000005',
    'default',
    'North',
    'Uttar Pradesh',
    'Lucknow',
    'Lucknow',
    'iON Digital Zone iDZ Gomti Nagar Extension',
    'CP-4, Sector 7, Gomti Nagar Extension',
    'Ground Floor',
    'LKO-LAB-1, LKO-LAB-2',
    500,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4048,
    50022
),
(
    'c1000000-0000-0000-0000-000000000006',
    'default',
    'North',
    'Rajasthan',
    'Jaipur',
    'Jaipur',
    'iON Digital Zone iDZ Sitapura',
    'RIICO Industrial Area, Sitapura',
    '1st & 2nd Floor',
    'JPR-LAB-A, JPR-LAB-B',
    450,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4043,
    50019
),
(
    'c1000000-0000-0000-0000-000000000007',
    'default',
    'North',
    'Chandigarh',
    'Chandigarh',
    'Chandigarh',
    'Chandigarh Online Examination Centre',
    'Plot 45, Industrial Area Phase 1',
    'Ground Floor',
    'CHD-CBT-1',
    400,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4054,
    50033
),

-- West Region (Maharashtra, Gujarat)
(
    'c1000000-0000-0000-0000-000000000008',
    'default',
    'West',
    'Maharashtra',
    'Mumbai Suburban',
    'Mumbai',
    'iON Digital Zone iDZ Powai',
    'Saki Vihar Road, Powai',
    '2nd Floor, Wing A',
    'MUM-POWAI-1, MUM-POWAI-2',
    650,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4036,
    50002
),
(
    'c1000000-0000-0000-0000-000000000009',
    'default',
    'West',
    'Maharashtra',
    'Pune',
    'Pune',
    'iON Digital Zone iDZ Hinjawadi Phase 1',
    'Rajiv Gandhi Infotech Park, Hinjawadi Phase 1',
    '1st Floor',
    'PUN-HINJ-1, PUN-HINJ-2',
    500,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4036,
    50003
),
(
    'c1000000-0000-0000-0000-000000000010',
    'default',
    'West',
    'Maharashtra',
    'Nagpur',
    'Nagpur',
    'Maharashtra Assessment Complex Ramdaspeth',
    'Central Avenue, Ramdaspeth',
    'Ground Floor',
    'NGP-CBT-1',
    400,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4036,
    50004
),
(
    'c1000000-0000-0000-0000-000000000011',
    'default',
    'West',
    'Gujarat',
    'Ahmedabad',
    'Ahmedabad',
    'iON Digital Zone iDZ SG Highway',
    'Near Vaishnodevi Circle, SG Highway',
    '1st & 2nd Floor',
    'AMD-SGH-1, AMD-SGH-2',
    500,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4029,
    50016
),

-- South Region (Karnataka, Telangana, Tamil Nadu, Kerala, Andhra Pradesh)
(
    'c1000000-0000-0000-0000-000000000012',
    'default',
    'South',
    'Karnataka',
    'Bengaluru Urban',
    'Bengaluru',
    'iON Digital Zone iDZ Electronic City Phase 2',
    'Tech Park Campus, Electronic City Phase 2',
    'Ground, 1st & 2nd Floor',
    'BLR-EC-01, BLR-EC-02, BLR-EC-03',
    700,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4033,
    50006
),
(
    'c1000000-0000-0000-0000-000000000013',
    'default',
    'South',
    'Telangana',
    'Medchal-Malkajgiri',
    'Hyderabad',
    'iON Digital Zone iDZ Moula Ali',
    'Industrial Development Area, Moula Ali',
    '1st Floor',
    'HYD-MA-1, HYD-MA-2',
    600,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4046,
    50012
),
(
    'c1000000-0000-0000-0000-000000000014',
    'default',
    'South',
    'Tamil Nadu',
    'Chennai',
    'Chennai',
    'iON Digital Zone iDZ Ambattur',
    'Ambattur Industrial Estate, South Phase',
    'Ground & 1st Floor',
    'CHE-AMB-1, CHE-AMB-2',
    550,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4045,
    50009
),
(
    'c1000000-0000-0000-0000-000000000015',
    'default',
    'South',
    'Tamil Nadu',
    'Coimbatore',
    'Coimbatore',
    'National Assessment Facility Peelamedu',
    'Avinashi Road, Peelamedu',
    '2nd Floor',
    'CBE-PEEL-1',
    350,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4045,
    50010
),
(
    'c1000000-0000-0000-0000-000000000016',
    'default',
    'South',
    'Andhra Pradesh',
    'Tirupati',
    'Tirupati',
    'Tirupati Digital Assessment Complex',
    'Renigunta Road, Industrial Corridor',
    '1st Floor',
    'TPT-CBT-1',
    350,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4023,
    50044
),
(
    'c1000000-0000-0000-0000-000000000017',
    'default',
    'South',
    'Kerala',
    'Ernakulam',
    'Kochi',
    'iON Digital Zone iDZ Kalamassery',
    'HMT Junction, Kalamassery',
    '1st Floor',
    'COK-KAL-1',
    400,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4034,
    50015
),

-- East & North-East Region (West Bengal, Odisha, Bihar, Jharkhand, Assam)
(
    'c1000000-0000-0000-0000-000000000018',
    'default',
    'East',
    'West Bengal',
    'North 24 Parganas',
    'Kolkata',
    'iON Digital Zone iDZ Salt Lake Sector V',
    'Block EP & GP, Sector V, Salt Lake',
    '3rd Floor, Tower B',
    'CCU-SLV-1, CCU-SLV-2',
    650,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4050,
    50031
),
(
    'c1000000-0000-0000-0000-000000000019',
    'default',
    'East',
    'Odisha',
    'Khordha',
    'Bhubaneswar',
    'Odisha Online Examination Complex Patia',
    'Infocity Area, Patia',
    'Ground & 1st Floor',
    'BBI-PAT-1',
    450,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4041,
    50041
),
(
    'c1000000-0000-0000-0000-000000000020',
    'default',
    'East',
    'Bihar',
    'Patna',
    'Patna',
    'iON Digital Zone iDZ Patliputra',
    'Patliputra Industrial Area',
    '1st Floor',
    'PAT-CBT-1, PAT-CBT-2',
    500,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4026,
    50030
),
(
    'c1000000-0000-0000-0000-000000000021',
    'default',
    'East',
    'Jharkhand',
    'Ranchi',
    'Ranchi',
    'Jharkhand Assessment Hub Namkum',
    'Namkum Industrial Area',
    'Ground Floor',
    'RNC-LAB-1',
    400,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4032,
    50038
),
(
    'c1000000-0000-0000-0000-000000000022',
    'default',
    'North-East',
    'Assam',
    'Kamrup Metropolitan',
    'Guwahati',
    'North East Regional Testing Centre Borjhar',
    'VIP Road, Near Airport, Borjhar',
    '1st Floor',
    'GAU-CBT-1',
    350,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4025,
    50045
),

-- Central Region (Madhya Pradesh, Chhattisgarh)
(
    'c1000000-0000-0000-0000-000000000023',
    'default',
    'Central',
    'Madhya Pradesh',
    'Indore',
    'Indore',
    'iON Digital Zone iDZ Vijay Nagar',
    'A.B. Road, Scheme No. 54, Vijay Nagar',
    '2nd Floor',
    'IDR-VJN-1',
    450,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4035,
    50029
),
(
    'c1000000-0000-0000-0000-000000000024',
    'default',
    'Central',
    'Madhya Pradesh',
    'Bhopal',
    'Bhopal',
    'MP Online Examination Hub MP Nagar',
    'Zone-II, Maharana Pratap Nagar',
    '1st Floor',
    'BPL-MPN-1',
    400,
    TRUE,
    NOW(),
    NOW(),
    0,
    101,
    4035,
    50028
)
ON CONFLICT (id) DO NOTHING;

-- ════════════════════════════════════════════════════════════════
-- SEED DATA: Examinations, Schedules, Shifts & Seat Allocations
-- ════════════════════════════════════════════════════════════════

-- Seed Examinations
INSERT INTO examination_service.examination (
    id,
    tenant_id,
    name,
    code,
    conducting_authority,
    category,
    examination_type,
    academic_year,
    examination_mode,
    duration_minutes,
    total_marks,
    negative_marking_enabled,
    negative_marking_value,
    navigation_policy,
    calculator_policy,
    review_flag_enabled,
    sections_json,
    status,
    created_by,
    created_at,
    updated_at,
    version
) VALUES
(
    'e1000000-0000-0000-0000-000000000001',
    'default',
    'Staff Selection Commission Combined Graduate Level (SSC CGL) Tier-1 Examination 2026',
    'SSC-CGL-TIER1-2026',
    'Staff Selection Commission (SSC)',
    'RECRUITMENT',
    'PRELIMINARY',
    '2026-27',
    'CBT',
    60,
    200,
    TRUE,
    0.50,
    'FLEXIBLE',
    'NONE',
    TRUE,
    '[
        {"name":"General Intelligence and Reasoning","subject":"General Intelligence and Reasoning","questionCount":25,"marksPerQuestion":2.0,"negativeMarksPerQuestion":0.5},
        {"name":"General Awareness","subject":"General Awareness","questionCount":25,"marksPerQuestion":2.0,"negativeMarksPerQuestion":0.5},
        {"name":"Quantitative Aptitude","subject":"Quantitative Aptitude / Mathematical Abilities","questionCount":25,"marksPerQuestion":2.0,"negativeMarksPerQuestion":0.5},
        {"name":"English Comprehension","subject":"English Language and Comprehension","questionCount":25,"marksPerQuestion":2.0,"negativeMarksPerQuestion":0.5}
    ]'::jsonb,
    'PUBLISHED',
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'e1000000-0000-0000-0000-000000000002',
    'default',
    'IBPS Probationary Officer (PO) Preliminary Examination 2026',
    'IBPS-PO-PRE-2026',
    'Institute of Banking Personnel Selection (IBPS)',
    'RECRUITMENT',
    'PRELIMINARY',
    '2026-27',
    'CBT',
    60,
    100,
    TRUE,
    0.25,
    'RESTRICTED',
    'NONE',
    TRUE,
    '[
        {"name":"English Language","subject":"English Language and Comprehension","questionCount":30,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.25},
        {"name":"Quantitative Aptitude","subject":"Quantitative Aptitude / Mathematical Abilities","questionCount":35,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.25},
        {"name":"Reasoning Ability","subject":"General Intelligence and Reasoning","questionCount":35,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.25}
    ]'::jsonb,
    'PUBLISHED',
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'e1000000-0000-0000-0000-000000000003',
    'default',
    'UPSC Civil Services (Preliminary) Examination 2026 - Paper 1 (General Studies)',
    'UPSC-CSE-PRE-GS1-2026',
    'Union Public Service Commission (UPSC)',
    'RECRUITMENT',
    'PRELIMINARY',
    '2026-27',
    'CBT',
    120,
    200,
    TRUE,
    0.66,
    'FLEXIBLE',
    'NONE',
    TRUE,
    '[
        {"name":"General Studies","subject":"General Studies","questionCount":100,"marksPerQuestion":2.0,"negativeMarksPerQuestion":0.66}
    ]'::jsonb,
    'PUBLISHED',
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'e1000000-0000-0000-0000-000000000004',
    'default',
    'Railway Recruitment Board Non-Technical Popular Categories (RRB NTPC) CBT-1 2026',
    'RRB-NTPC-CBT1-2026',
    'Railway Recruitment Board (RRB)',
    'RECRUITMENT',
    'PRELIMINARY',
    '2026-27',
    'CBT',
    90,
    100,
    TRUE,
    0.33,
    'FLEXIBLE',
    'NONE',
    TRUE,
    '[
        {"name":"General Awareness","subject":"General Awareness","questionCount":40,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.33},
        {"name":"Mathematics","subject":"Mathematics","questionCount":30,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.33},
        {"name":"General Intelligence disciplined Reasoning","subject":"General Intelligence and Reasoning","questionCount":30,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.33}
    ]'::jsonb,
    'PUBLISHED',
    NULL,
    NOW(),
    NOW(),
    0
),
(
    'e1000000-0000-0000-0000-000000000005',
    'default',
    'Central Teacher Eligibility Test (CTET) Paper-1 (Primary Teacher) 2026',
    'CTET-PAPER1-2026',
    'Central Board of Secondary Education (CBSE)',
    'ENTRANCE',
    'PRELIMINARY',
    '2026-27',
    'CBT',
    150,
    150,
    FALSE,
    0.0,
    'FLEXIBLE',
    'NONE',
    TRUE,
    '[
        {"name":"Child Development and Pedagogy","subject":"Child Development and Pedagogy","questionCount":30,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.0},
        {"name":"Mathematics","subject":"Mathematics","questionCount":30,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.0},
        {"name":"Environmental Studies","subject":"General Studies","questionCount":30,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.0},
        {"name":"Language I (Hindi)","subject":"General Hindi","questionCount":30,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.0},
        {"name":"Language II (English)","subject":"English Language and Comprehension","questionCount":30,"marksPerQuestion":1.0,"negativeMarksPerQuestion":0.0}
    ]'::jsonb,
    'PUBLISHED',
    NULL,
    NOW(),
    NOW(),
    0
)
ON CONFLICT (id) DO NOTHING;

-- Seed Schedules
INSERT INTO examination_service.examination_schedule (
    id,
    tenant_id,
    examination_id,
    schedule_name,
    schedule_version,
    notification_number,
    exam_date,
    reserve_date,
    time_zone,
    status,
    change_reason,
    effective_from,
    previous_version_id,
    created_by,
    modified_by,
    approved_by,
    approved_at,
    created_at,
    updated_at,
    version
) VALUES
(
    'b1000000-0000-0000-0000-000000000001',
    'default',
    'e1000000-0000-0000-0000-000000000001',
    'SSC CGL Tier-1 Phase-1 Examination Schedule',
    1,
    'SSC/HQ/CGL/2026-01',
    '2026-10-15',
    '2026-10-18',
    'Asia/Kolkata',
    'PUBLISHED',
    NULL,
    '2026-10-15',
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(),
    NOW(),
    NOW(),
    0
),
(
    'b1000000-0000-0000-0000-000000000002',
    'default',
    'e1000000-0000-0000-0000-000000000002',
    'IBPS PO Prelims All-India Schedule',
    1,
    'IBPS/CRP-PO/XIV/2026',
    '2026-11-01',
    '2026-11-03',
    'Asia/Kolkata',
    'PUBLISHED',
    NULL,
    '2026-11-01',
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(),
    NOW(),
    NOW(),
    0
),
(
    'b1000000-0000-0000-0000-000000000003',
    'default',
    'e1000000-0000-0000-0000-000000000004',
    'RRB NTPC CBT-1 Stage-1 Examination Schedule',
    1,
    'RRB/CEN/01/2026',
    '2026-11-20',
    '2026-11-25',
    'Asia/Kolkata',
    'PUBLISHED',
    NULL,
    '2026-11-20',
    NULL,
    NULL,
    NULL,
    NULL,
    NOW(),
    NOW(),
    NOW(),
    0
)
ON CONFLICT (id) DO NOTHING;

-- Seed Shifts
INSERT INTO examination_service.exam_shift (
    id,
    tenant_id,
    schedule_id,
    shift_number,
    shift_name,
    reporting_time,
    gate_closing_time,
    login_start_time,
    exam_start_time,
    exam_end_time,
    exit_time,
    duration_minutes,
    buffer_minutes,
    created_at,
    updated_at,
    version
) VALUES
(
    'f1000000-0000-0000-0000-000000000001',
    'default',
    'b1000000-0000-0000-0000-000000000001',
    1,
    'Shift 1 - Morning',
    '07:30:00',
    '08:30:00',
    '08:45:00',
    '09:00:00',
    '10:00:00',
    '10:15:00',
    60,
    15,
    NOW(),
    NOW(),
    0
),
(
    'f1000000-0000-0000-0000-000000000002',
    'default',
    'b1000000-0000-0000-0000-000000000001',
    2,
    'Shift 2 - Afternoon',
    '11:00:00',
    '12:00:00',
    '12:15:00',
    '12:30:00',
    '13:30:00',
    '13:45:00',
    60,
    15,
    NOW(),
    NOW(),
    0
),
(
    'f1000000-0000-0000-0000-000000000003',
    'default',
    'b1000000-0000-0000-0000-000000000001',
    3,
    'Shift 3 - Evening',
    '14:30:00',
    '15:30:00',
    '15:45:00',
    '16:00:00',
    '17:00:00',
    '17:15:00',
    60,
    15,
    NOW(),
    NOW(),
    0
),
(
    'f1000000-0000-0000-0000-000000000004',
    'default',
    'b1000000-0000-0000-0000-000000000002',
    1,
    'Shift 1 - Morning',
    '07:30:00',
    '08:30:00',
    '08:45:00',
    '09:00:00',
    '10:00:00',
    '10:15:00',
    60,
    15,
    NOW(),
    NOW(),
    0
),
(
    'f1000000-0000-0000-0000-000000000005',
    'default',
    'b1000000-0000-0000-0000-000000000003',
    1,
    'Shift 1 - Morning',
    '08:00:00',
    '09:00:00',
    '09:15:00',
    '09:30:00',
    '11:00:00',
    '11:15:00',
    90,
    15,
    NOW(),
    NOW(),
    0
)
ON CONFLICT (id) DO NOTHING;

-- Seed Shift Seat Allocations
INSERT INTO examination_service.shift_seat_allocation (
    id,
    tenant_id,
    shift_id,
    centre_id,
    total_seats,
    available_seats,
    reserved_seats,
    pwd_seats,
    emergency_buffer_seats,
    female_reserved_seats,
    special_category_seats,
    created_at,
    updated_at,
    version
) VALUES
(
    'a2000000-0000-0000-0000-000000000001',
    'default',
    'f1000000-0000-0000-0000-000000000001',
    'c1000000-0000-0000-0000-000000000001',
    600,
    550,
    50,
    20,
    10,
    15,
    5,
    NOW(),
    NOW(),
    0
),
(
    'a2000000-0000-0000-0000-000000000002',
    'default',
    'f1000000-0000-0000-0000-000000000001',
    'c1000000-0000-0000-0000-000000000002',
    550,
    500,
    50,
    20,
    10,
    15,
    5,
    NOW(),
    NOW(),
    0
),
(
    'a2000000-0000-0000-0000-000000000003',
    'default',
    'f1000000-0000-0000-0000-000000000001',
    'c1000000-0000-0000-0000-000000000008',
    650,
    600,
    50,
    25,
    10,
    15,
    0,
    NOW(),
    NOW(),
    0
),
(
    'a2000000-0000-0000-0000-000000000004',
    'default',
    'f1000000-0000-0000-0000-000000000001',
    'c1000000-0000-0000-0000-000000000012',
    700,
    650,
    50,
    25,
    10,
    15,
    0,
    NOW(),
    NOW(),
    0
),
(
    'a2000000-0000-0000-0000-000000000005',
    'default',
    'f1000000-0000-0000-0000-000000000001',
    'c1000000-0000-0000-0000-000000000018',
    650,
    600,
    50,
    25,
    10,
    15,
    0,
    NOW(),
    NOW(),
    0
)
ON CONFLICT (id) DO NOTHING;
