/*
 * SPDX-License-Identifier: AGPL-3.0-only
 *
 * Open Digital Public Infrastructure (DPI) Platform
 * Copyright (C) 2025 Open Digital Public Infrastructure (DPI) Platform Contributors
 */

syntax = "proto3";

package com.examplatform.examination.grpc;

option java_multiple_files = true;
option java_package = "com.examplatform.examination.grpc";
option java_outer_classname = "ExaminationProto";

service ShiftAssignmentGrpcService {
  rpc GetShiftAssignment (ShiftAssignmentGrpcRequest) returns (ShiftAssignmentGrpcResponse);
}

message ShiftAssignmentGrpcRequest {
  string candidate_id = 1;
  string exam_id = 2;
  string shift_id = 3;
  string tenant_id = 4;
}

message ShiftAssignmentGrpcResponse {
  string assignment_id = 1;
  string paper_id = 2;
  int32 duration_minutes = 3;
  int32 extra_time_minutes = 4;
  string exam_shift_id = 5;
  bool is_assigned = 6;
}
